### ISSUE TITLE
Handling nulls: pointers vs structs vs methods

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#1]
There are two ways to handle SQL null values in Go: pointers and structs like NullString, NullInt, and so on.
This issue serves to describe solutions and discuss what users prefer.

### 1) Pointers

```go
import (
  "log"
)

type User struct {
  // Name is required
  Name string

  // Email is optional/nullable
  Email *string
}

func main() {
  user, err := photon.User.FindOne()

  if user.Email == nil {
    log.Printf("user has filled his email: %s", user.Email)

    // can dereference safely here
    checkValidEmail(*user.Email)
  }

  // if not checking beforehand
  // if Email is nil this will result in a panic
  checkValidEmail(*user.Email)
}
```

Advantages are simplicity and clean syntax. It could be dangerous because you can get a runtime panic if you dereference the pointer without checking it first. 

#### Advantages
- simple, clean syntax

#### Problems
- not the Go way of handling nulls

#### Notes
- may panic if a variable is not checked before de-referencing (can be an advantage or disadvantage; can break the
 app but may be better then failing silently)

### 2) Null-Structs

```go
import (
  "log"
)

// similar to sql.NullString
type NullString struct {
  Value string
  Valid bool
}

type User struct {
  // Name is required
  Name string

  // Email is optional/nullable
  Email NullString
  // other types could have NullInt, NullTime, etc.
}

func main() {
  user, err := photon.User.FindOne()

  if user.Email.Valid {
    log.Printf("user has filled his email: %s", user.Email.Value)

    checkValidEmail(user.Email.Value)
  }

  // if valid is null, this will silently pass with Email.Value == ""
  checkValidEmail(user.Email.Value)
}
```

This is the way the native Go database/sql package works.

#### Problems
- adds verbosity by using .Valid and .Value fields
- while it may be suited better to handle nulls, structs are usually also not used to handle nulls

### 3) Methods

This is a new idea from @robojones, please see the comment https://github.com/prisma/photongo/issues/1#issuecomment-536520519.

```go
func main() {
  user, err := photon.User.FindOne()

  email, ok := user.Email()
  if ok {
    log.Printf("user has filled his email: %s", email)

    checkValidEmail(email)
  }

  // if the user's email is null, the Go default string value ("") will be passed
  // this is probably the best way as you can often still check for nulls in the passEmail function, which would equal to "" in Go 
  passEmail(email)
}
```

#### Advantages:
- Probably the most Go-like way, as neither pointers nor structs should be used for nullability
- similar to standard libraries: `key, ok := os.LookupEnv("key")`

#### Problems
- may be hard to pass if you explicitly want to pass the value with the null information

**What would you prefer?**

**Comment by darioielardi** [comment]
I agree with your point about dereferencing a nil pointer in the first option:

> can be an advantage or disadvantage; can break the
> app but may be better then failing silently

Both can lead to undesirable behaviors, but it would be easier to debug in the first case ( pointers ).

Also, would be nice to have a more idiomatic Go-way to handle this, but Null-structs add too much verbosity in my opinion.

**Comment by kandros** [comment]
I like the second better, it’s more go idiomatic and safer in general

**Comment by afunnydev** [comment]
Personally prefer the first option for simplicity of syntax compared to Null-structs

**Comment by robojones** [comment]
I agree with @kandros. Especially for users coming from other SQL clients it would be more intuitive to have a NullString similar to the one in [the native go sql package](https://golang.org/pkg/database/sql/). You could even import the NullString, NullBool,... structs from there instead of generating them in the client.

**Comment by steebchen** [comment]
There could also be a third option: default to one solution but make it configurable, so that each individual user can decide what solutions fits best.

**Comment by robojones** [comment]
I had an idea which I quite like. When using the NullString solution, the user may easily forget to check the `Valid` property before using the `Value`.

```go
if user.Name.Valid { // users may accidentally forget this check.
  fmt.Printf("Not null: %s", user.Name.Value)
}
```

So instead of using `NullStrings` or pointers for nullability, I thought of a third option. We could create a multi-value getter for each property. It returns two values: The actual `value` of the field and an `ok` boolean. `ok` is true if the value is not null. This encourages the user to check for the ok value because the go compiler requires you to handle all return parameters of the getter.

```go
if name, ok := user.Name(); ok {
  fmt.Printf("Not null: %s", name)
}
```

If the user does not want to check the ok value, he can explicitly ignore it.

```go
name, _ = user.Name()
```

**Comment by matthewmueller** [comment]
This is a very interesting approach. I like that Go will complain if you don't provide `ok` or `_`. A couple considerations:

- would all of the outputs would be functions?
- if we do a hybrid (only functions for nullables) would that be confusing?

I'd like to see 3 real-world comparisons to help with making decisions:

1. .Value comparison
2. pointer comparison
3. ok comparison

**Comment by robojones** [comment]
@matthewmueller I would say that all output fields should be functions for consistency. We could make it so that for required fields the getter only has one return value; the `ok` is omitted.  Also, using getters for all fields would allow the usage of interfaces, when passing the user to another function (e.g. for dependency injection).
```go
func Login(user string, password string) {
  user, err := photon.User.FindOne()

  if CheckPassword(user, password) {
    // do something
  }
}

// CheckPasswordUser only specifies the fields of the user which
// are used by the CheckPassword function.
// This means that it is possible to test the CheckPassword function using
// another implementation of CheckPasswordUser.
type CheckPasswordUser interface {
  PasswordHash() (v string, ok bool)
  PasswordSalt() (v string, ok bool)
}

func CheckPassword(user CheckPasswordUser, password string) (verified bool) {
  // to password hashing and stuff
}
```

**Comment by steebchen** [comment]
One advantage of using mixed fields and methods is that it may be more readable to know if a field is nullable or not, while it's less obvious when all methods are methods. Plus, it increases verbosity. @robojones either case I think the interface passing is not very intuitive and should be avoided either way.

**Comment by steebchen** [comment]
For the reasons and discussion listed above, we have for now decided to go with the new "methods" way.
