### ISSUE TITLE
How to optionally add fields to CreateOne

### ISSUE THREAD

**Issue by dwaynelavon** [prisma/prisma-client-go#106]
If I have a model with an optional field. how do I optionally pass that value to CreateOne

``` 
model User {
  id String @default(cuid()) @id
  phoneNumber Int?
}
```

I can't use the param value of phoneNumber because it's a pointer.  

```
func Create(ctx context.Context, phoneNumber *int) error {
  client.CreateOne(
    db.User.PhoneNumber.Set(phoneNumber)
  )
  return nil
}
```

**Comment by steebchen** [comment]
I have created https://github.com/prisma/prisma-client-go/pull/108. With that PR, you can now use `.SetOptional(...)` which takes a pointer. Does that sound good to you?

**Comment by dwaynelavon** [comment]
@steebchen Looks good. That's the exact method I was searching for
