### ISSUE TITLE
Matching multiple conditions

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#159]
I have a schema like

```
model User {
    id        String   @default(cuid()) @id
    rooms        Room[]
}

model Room {
     id           String    @id
     participants User[]
}
```

I'd like to query to see if a user is a participant of a room. What is the best way to do this? I want to do something like `select user where User.ID == uid && User.Rooms.contains(rid)`

**Comment by steebchen** [comment]
I think you could query as follows:

```go
func IsUserInRoom(uid string, rid string) *db.UserModel {
	users, err := NewClient().User.FindMany(
		User.ID.Equals(uid),
		User.Rooms.Some(
			Room.ID.Equals(rid),
		),
	).Exec(ctx)
	// check err

	if len(users) > 0 {
		return users[0]
	}

	return nil
}
```

If len(slice) is 0, there is no such user. If there is one result, that user has the id `uid` and is part of the room `rid`.

**Comment by tarrencev** [comment]
awesome. thanks!
