### ISSUE TITLE
Returning relations after creation

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#164]
I have some code like this to create a meeting. It creates the room then assigns it to the meeting.

```
a := &AuthContext{...}
createdRoom, err := db.Client.Room.CreateOne(
	types.Room.ID.Set(...),
	types.Room.Owner.Link(types.User.ID.Equals(a.User.ID)),
	types.Room.Participants.Link(types.User.ID.Equals(a.User.ID)),
).Exec(ctx)

createdMeeting, err := db.Client.Meeting.CreateOne(
	types.Meeting.Owner.Link(types.User.ID.Equals(a.User.ID)),
	types.Meeting.Start.Set(start),
	types.Meeting.Room.Link(types.Room.ID.Equals(createdRoom.ID)),
	types.Meeting.End.SetOptional(input.End),
).Exec(ctx)
```

I then want to return a `Meeting` type with relations like

```
{
    room: {
        id: ...,
    }
}
```

But the `createdMeeting` does not contain relations. Is it possible to have the `CreateOne` method return relations? Or should I manually add them doing something like

```
createdMeeting.RelationsMeeting.Room = &createdRoom
```

**Comment by steebchen** [comment]
I guess for this specific code you wouldn't need to do that, since you already have `createdRoom` available. It's a good feature request though.
