### ISSUE TITLE
Unlink relation

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#169]
Sorry for all the questions.

I'm trying to figure out how to unlink a relation, for example, reverse this

```
       update, err := db.Client.Room.FindOne(types.Room.ID.Equals(rid)).Update(
		types.Room.Participants.Link(types.User.ID.Equals(uid)),
	).Exec(ctx)
```

**Comment by steebchen** [comment]
There should be a .Unlink() method, it seems I forgot about that... I'll fix this ASAP.

By the way, for questions, there's now a #prisma-client-go channel in our [public slack](https://slack.prisma.io).

**Comment by steebchen** [comment]
@tarrencev I just added an .Unlink() method – please try it out in @master and let me know if it shouldn't work as expected.
