### ISSUE TITLE
Consider adding a helper method to return a slice of raw models

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#171]
If I have a case like

```go
user, err := db.Client.User.FindMany(
    db.User.Name.Contains(query),
).Exec(ctx)
```

How do I convert `[]db.UserModel` to `[]db.RawUser`?

We could add automatically generated helper methods to convert between these slices. These could even be types of custom slice types (`type UserSlice []User`) so we can define a method on that type – but this may have unintended side effects.

As suggested by @tarrencev, we could also introduce a chain method which would return that type:

```go
user, err := db.Client.User.FindMany(
	db.User.ID.Equals(id),
).Raw().Exec(ctx)
```

Or even (by @matthewmueller):

```go
user, err := db.Client.User.FindMany(
	db.User.ID.Equals(id),
).Raw(ctx)
```

**Comment by matthewmueller** [comment]
let's also consider renaming `Raw` since it's an entirely different concept than `Raw` queries. This is more like getting the POJO (plain old javascript object), in our case POGS (plain old javascript struct/slice).

Some possibilities:

- Inner
- Output

Not in love with either, if you have any ideas please let us know!

**Comment by steebchen** [comment]
I think `Inner` is probably a good choice for now. At least better than Raw, which may be confused with unrelated raw queries.

**Comment by matthewmueller** [comment]
Sounds good.

**Comment by tarrencev** [comment]
Would love to land this soon :)

**Comment by steebchen** [comment]
A common use case for this is to use it with incompatible libraries such as gqlgen. I'll build this feature soon to have a temporary fits-all solution, however ideally we will make it compatible with gqlgen directly which is tracked in #371.

**Comment by steebchen** [comment]
I need to make a final decision on syntax.

WDYT about this:

```
user, err := db.Client.User.FindMany(
	db.User.ID.Equals(id),
).ExecInternal(ctx)

// or

user, err := db.Client.User.FindMany(
	db.User.ID.Equals(id),
).InternalExec(ctx)
```

Right now the struct is called "Internal", which is why this method would be called InternalX as well.

Now that I think about this method, internal sounds kinda weird, "inner" would probably make more sense. However if we would change the name it would be a breaking change for users depending on the internal structs.

**Comment by matthewmueller** [comment]
FWIW, Internal makes me think I'm doing something I shouldn't be doing. Calling some internal Prisma Client method. Your call though.

> Now that I think about this method, internal sounds kinda weird, "inner" would probably make more sense. However if we would change the name it would be a breaking change for users depending on the internal structs.

Deprecate & alias?

**Comment by steebchen** [comment]
Yeah exactly. I don't remember why I chose this wording back then :(

I think it may be worth deprecating Internal and renaming to Inner; that should be fairly simple to do in the generator templates.
