### ISSUE TITLE
@@unique constraint does not work

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#179]
`go run github.com/prisma/prisma-client-go generate` hangs indefinitely when the db model includes a constraint like `@@unique([userId, eventId], name: "ParticipantUserEvent_key")`

**Comment by steebchen** [comment]
I can’t reproduce. Can you please send a full model (or better, full schema) where this happens? Maybe you can also set the env var `DEBUG=*` to see if there are any logs?

**Comment by steebchen** [comment]
Could reproduce. I also renamed the issue, as it's actually about a specific error and not about a hanging command (which is instead tracked in #181).

**Comment by steebchen** [comment]
Released in v4.0.0.
