### ISSUE TITLE
@@unique currentely not supported ?

### ISSUE THREAD

**Issue by maaft** [prisma/prisma-client-go#191]
schema.prisma:
```typescript
datasource db {
    provider = "sqlite"
    url      = "file:dev.db"
}

generator db {
    provider = "go run github.com/prisma/prisma-client-go"
    output = "./db/db_gen.go"
    package = "db"
}

model Customer {
  id              String   @id @default(cuid())
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt

  name            String
  phone           String
  email           String

  @@unique([name, phone, email])
}
```

Generating the client with `go run github.com/prisma/prisma-client-go generate` does not give any output and the client is not generated.

When I omit the `@@unique` constraint, the client is sucessfully generated.

**Comment by steebchen** [comment]
Can you please specify what version you're on? Can you try adding `go get github.com/prisma/prisma-client-go@master` to see if it works with the latest dev version?

**Comment by maaft** [comment]
Thank you very much!

The addition of `@master` solved this issue.

**Comment by steebchen** [comment]
Great, thanks! I'll soon release these fixes in a new tag.

**Comment by steebchen** [comment]
Duplicate of #179. Released in v4.0.0.

**Comment by maaft** [comment]
wow, from v0.0.3 to v4.0.0! That must be a huge step forward! ;-) :-P

**Comment by steebchen** [comment]
Oops, thanks for the hint! At least I named the tag correctly :P
