### ISSUE TITLE
Disable debug output by default

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-go#196]
Given this `main.go`:

```go
package main

import (
	"fmt"

	"github.com/prisma/demo-go/db"
)

func main() {
	client := db.NewClient()
	err := client.Connect()
	if err != nil {
		panic(err)
	}

	defer func() {
		err := client.Disconnect()
		if err != nil {
			panic(fmt.Errorf("could not disconnect %w", err))
		}
	}()
}

```

Running `go run main.go`, I first get:

```
info: 2020/07/15 11:28:49 no query engine defined or found
info: 2020/07/15 11:28:49 if you want to pre-fetch the query engine for better startup performance, specify `binaryTargets = ["native"]` in your Schema.prisma file under "generator" and upload the query engine with your application.
info: 2020/07/15 11:28:49 fetching the query engine now...
info: 2020/07/15 11:28:50 done.
Printing to stderr for debugging
Listening on 127.0.0.1:60190
```

And subsequent runs I get:

```
Printing to stderr for debugging
Listening on 127.0.0.1:60247
``` 

**Problem**

As a new user, I don't care about this information. It's telling me things that don't matter at all to me when I'm just evaluating Prisma Go. `Listening on 127.0.0.1:60247` is confusing because I didn't start a server. 

**Suggested Changes**

1. Allow one to pass in a logger or provide a log level flag to see this debug information
2. `Listening on 127.0.0.1:60247` => `Query engine is listening on 127.0.0.1:60247`

**Comment by steebchen** [comment]
We just pipe whatever the query engine logs which is mostly used for error logging. I guess we should be able to only log errors and not debugging output from the query engine.

**Comment by matthewmueller** [comment]
Sounds good. I'd follow whatever JS client does here.
