### ISSUE TITLE
Chaining relations

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-go#198]
**Problem**

JS Client supports chained relations, but the Go client does not

```js
const postsByUser: Post[] = await prisma.user
  .findOne({ where: { email: 'alice@prisma.io' } })
  .posts()
```

**Suggested Solution**

```go
posts, err := client.User.FindOne(...).Posts(...).Exec(ctx)
```

**Comment by steebchen** [comment]
duplicate of https://github.com/prisma/prisma-client-go/issues/104 and was abandoned due to https://github.com/prisma/prisma-client-go/issues/104#issuecomment-624567858
