### ISSUE TITLE
Return multiple things at once

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#2]
Assuming we have the following datamodel:

```prisma
model Post {
  id     ID      @id
  title  String
  author User
}

model User {
  id    ID     @id
  name  String
  posts Post[]
}
```

The goal is to fetch multiple things at once, e.g. a user with his posts. The main problem is that Go can't return more struct fields dynamically, but we still want a (mostly) type safe solution.

My proposal:

Photon generates structs with all relations:

```go
type User struct {
  ID    string
  Name  string
  Posts []Post
}
```

Fetch just a user:

```go
user, err := photon.User.FindOne.Where(
  photon.User.Email.Equals("hi@prisma.io"),
).Exec(ctx)

// user.Posts == nil
// len(user.Posts) == 0
```

Fetch a user and their posts:

```go
user, err := photon.User.FindOne.Where(
  photon.User.Email.Equals("hi@prisma.io"),
).With(
  photon.User.Posts.Limit(10),
).Exec(ctx)

// user.Posts will contain the user's posts with a limit of 10
```

Thanks to @robojones for the `.With(...)` syntax idea.

Feedback or other approaches (even if they're completely different) are very welcome!

**Comment by darioielardi** [comment]
Honestly your solution looks really good. I don't see any disadvantage, and it's a very clean syntax compared to Prisma 1 Go client.

**Comment by afunnydev** [comment]
Same here: love this approach! What would the suggested approach look like for types with more than one field referencing struct of other types? For example,

```
type User struct {
  ID       string
  Name     string
  Posts    []Post
  Comments []Comment
}
```

**Comment by steebchen** [comment]
@afunnydev Yes, the struct would reference all relations, and they default all to `nil`. If you want to fetch a relation you have to query it explicitly; as nested as you want.

**Comment by robojones** [comment]
Love the idea, @steebchen! I wish I had ideas like that. The new photongo client will be awesome.

**Comment by andcan** [comment]
Good idea, but I think relations should be treated the same way as proposed in #1:
```
type Posts struct {
  Values []Post
  Valid bool
}
```
This allows to distinguish between empty and unfetched relations.

**Comment by steebchen** [comment]
While this is an acceptable solution, it means that the related fields are not really type-safe. Another promising, but more complex, way to do this would be code generation as proposed in #9.

**Comment by alexdor** [comment]
Another inspiration could be this project https://github.com/volatiletech/sqlboiler , it uses code generation to generate a typesafe orm for go

**Comment by steebchen** [comment]
Thanks for the link. I'll check out sqlboiler in the next few weeks, it seems they have a very promising API!

**Comment by steebchen** [comment]
You can already query for relations using custom structs, but it’s ugly:

```go
type PostResponse struct {
	PostModel
	Author UserModel `json:"author"`
}
type Result struct {
	FindManyPost []PostResponse `json:"findManyPost"`
}
var actual Result
err := client.Load(
	client.Post.FindMany(
		Post.Title.Equals("1"),
		Post.Author.Fetch().Load(),
	).Load(),
).Exec(ctx, &actual)
```

As an alternative, it’s easier to just provide a .With() syntax like initially planned (but with methods). It’s also not 100% typesafe, but it’s much cleaner:

```go
// internal
type Post struct {
	Name string
	// …
}

// single query
post, err := FindOne().Exec(ctx) // returns []Post


type PostWithRelations struct {
	Name string
	author User
	comments []Comment
	// …
}

func (s PostWithRelations) Comments() {
	if s.comments == nil {
		panic("comments were not loaded")
	}
	return s.comments
}

func (s PostWithRelations) Author() {
	if !s.author.loaded {
		panic("author were not loaded")
	}
	return s.Author
}

// with relations
post, err := client.Post.FindOne().With(
	Post.Author.Load(),
).Exec(ctx) // returns PostWithRelations, error

author := post.Author() // is of type User
log.Printf("post was written by %+v", author)

comments := post.Comments() // this will panic, since we didn't load comments in the query 
```

While both methods don’t provide 100% compile time safety, the latter method is way cleaner and still provides the same type safety. In other words, the former method is uglier and harder to write but doesn’t actually provide more value.

**Comment by dwaynelavon** [comment]
> comments := post.Comments() // this will panic, since we didn't load comments in the query 
> ```
> 

@steebchen Was there a reason you chose to panic instead of letting the consumer handle any errors that arise?

**Comment by steebchen** [comment]
@dwaynelavon Just to clarify, this method will only panic if you didn't ask for a given relations. I think panicking here makes the most sense, since it's hard to make this compile-time safe. The whole query results in a single request to the prisma engine, so if there happens an error on the sql level `err` will contain the error.

For example, this code will compile and run fine:

```
post, err := client.Post.FindOne().With(Post.Comments.Fetch()).Exec(ctx)
if err != nil {
  return err
}
// at this time, comments are already fetched and ready to be accessed
comments := post.Comments()
log.Printf("comments: %+v", comments)
```

This code will panic when access `.Comments()`:


```
post, err := client.Post.FindOne().Exec(ctx)
if err != nil {
  return err
}
comments := post.Comments() // <- panic! did not fetch comments
log.Printf("comments: %+v", comments)
```

Does that make sense?

**Comment by dwaynelavon** [comment]
> @dwaynelavon That definitely makes sense. I feel like that works for most use cases. I'm running into issues while using a generic transform function that takes Prisma model and transforms it to my domain model. That function does not know if the caller has asked for the relations or not. Some methods in my repo don't need to related values and don't add the `.With` arguments to the chain

I would expect to be able to check and see if the relation is available, and if it's not then move on.

``` go
  func transformModel(model MyPrismaModel) (MyDomainModel, error) {
    if relationField, ok := RelationField(); ok {
      // transform this value also
    }
    // continue on with the rest of the transformation. 
  }
```

**Comment by steebchen** [comment]
For this use case, you can access the internal value (you may need to update prisma-client-go to the latest master):

```
if model.RawUser.Email != nil {
  return model.RawUser.Email
}
```

and the same goes for relations:

```go
if model.RelationsUser.Posts != nil {
  return model.RelationsUser.Posts
}
```

If you have better suggestions for naming these fields, feel free to say so.
