### ISSUE TITLE
How to cascade delete things?

### ISSUE THREAD

**Issue by maaft** [prisma/prisma-client-go#201]
How can we cascade delete things?

E.g.
```
model User {
   id           String  @id
   posts     Posts[]
}

model Post {
   id           String @id
   user       User @relation(fields: [userId], references: [id])
   userId    String
}
```

When calling the `deleteUser` mutation I also want to delete all posts and sub-sub-sub-relations.

**Comment by steebchen** [comment]
This is probably a Prisma schema and migrate issue, please see https://github.com/prisma/prisma/issues/2810 for details and follow for updates.
