### ISSUE TITLE
.Update Query returns Integer instead of Structs

### ISSUE THREAD

**Issue by maaft** [prisma/prisma-client-go#202]
E.g.
```
posts, err := r.Client.Post.FindMany(
		db.Post.UserID.Equals(user.ID),
	).Update(db.Post.Deleted.Set(true)).Exec(ctx)
```
Is this intended behavior? From the Prisma2 docs I can assume that there the structs are returned.

This functionality would be handy for cascading soft-deletes (which I am trying to implement right now).

**Comment by maaft** [comment]
Okay, seems like that with using `.FindOne()` instead of `.FindMany()` the struct is returned.

Therefore I guess that this is by design? I.e. you don't always want to read all (potentially millions of) updated rows.

**Comment by steebchen** [comment]
Correct, it is by design :) Feel free to re-open if you have concerns/questions.

**Comment by maaft** [comment]
@steebchen 

Is there a parameter to enable such behavior? Otherwise I have to fetch all rows again after the update.

**Comment by steebchen** [comment]
Unfortunately it's not possible to do so right now.

**Comment by maaft** [comment]
Would be very helpful to have this feature. Unfortunately I cannot reopen this issue.

**Comment by steebchen** [comment]
I think this would need to have a feature request in the core (i.e. https://github.com/prisma/prisma) first, maybe you can check if there's already an issue there, and if not, create one.
