### ISSUE TITLE
Introduce Number Type Operations

### ISSUE THREAD

**Issue by maaft** [prisma/prisma-client-go#205]
E.g. increment, decrement, ...

See: https://github.com/prisma/prisma-client-js/issues/655

**Comment by steebchen** [comment]
This fully depends on the implementation in the prisma engines, so the Go client won't have this feature unless it's implemented in prisma in general. Also related: https://github.com/prisma/prisma-client-js/issues/775

**Comment by steebchen** [comment]
This is now implemented in the js client, so this just needs a few code changes. I'll hopefully get to it soon.

**Comment by steebchen** [comment]
This was already fixed in #271 and is in v0.0.10+
