### ISSUE TITLE
Client not generated v0.0.6

### ISSUE THREAD

**Issue by FranciscoMendes10866** [prisma/prisma-client-go#224]
This question is similar to issue # 78, I am currently using version 0.0.6 and unfortunately I am not able to generate my Prisma Client from the quickstart example.

I tried to add an absolute path to the provider, but it still didn't work.

I even tried to run the cmd "which prisma-client-go", but says it was not found.

I certainly used the cmd "go get github.com/prisma/prisma-client-go".

Q.: I started learning Go a little while ago out of curiosity.

**Comment by steebchen** [comment]
Can you please set `export DEBUG=*` and run the generation again? It looks like there is an error happening but it gets suppressed due to an error in the Prisma CLI.

**Comment by steebchen** [comment]
Also can you try just removing the "package" and "output" options from the generator block to just use the defaults? I also [adapted](https://github.com/prisma/prisma-client-go/pull/225) this in the documentation.

**Comment by FranciscoMendes10866** [comment]
> Also can you try just removing the "package" and "output" options from the generator block to just use the defaults? I also [adapted](https://github.com/prisma/prisma-client-go/pull/225) this in the documentation.

Oh my god. I did this and It worked.
Thank you so much!

**Comment by steebchen** [comment]
Thanks for letting me know – will make sure the docs are up to date next time. 👍
