### ISSUE TITLE
How to improve Timeout problems?

### ISSUE THREAD

**Issue by darmie** [prisma/prisma-client-go#227]
I keep getting a very very slow start whenever my server restarts or is redeployed. It used to be quick, but it takes too long these days and I worry!

```json
{
  "errors": [
    {
      "message": "could not find tracking information for order: Request failed: raw post: Post \"http://localhost:58197/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
      "path": [
        "trackOrder"
      ]
    }
  ],
  "data": null
}
```

**Comment by steebchen** [comment]
I'm not sure I follow. Can you maybe provide more information and describe specifically when a timeout happens and why you assume it happens? What would you expect to happen instead?

**Comment by darmie** [comment]
> I'm not sure I follow. Can you maybe provide more information and describe specifically when a timeout happens and why you assume it happens? What would you expect to happen instead?

The time out happens when I make a request, and this seems to happen a lot when a make a nested GraphQL request

**Comment by steebchen** [comment]
Can you please share your prisma.schema contents, the version of the go client and the query you are running?

**Comment by darmie** [comment]
go client version: `v0.11.3`

Unfortunately I can't share the Prisma schema here.

**Comment by steebchen** [comment]
Can you at least share the query with different names or something? Otherwise it'll be hard to help

**Comment by darmie** [comment]
> Can you at least share the query with different names or something? Otherwise it'll be hard to help

I have updated the comment

**Comment by steebchen** [comment]
How many rows do you have in your database? Did you try limiting the result using pagination?

**Comment by darmie** [comment]
> How many rows do you have in your database? Did you try limiting the result using pagination?

Not up to 20 rows, and I didn't limit it

**Comment by steebchen** [comment]
Does it happen all the time or only sometimes? You said that

> I keep getting a very very slow start whenever my server restarts or is redeployed

So is it correct that it only happens at the beginning of running the code? Not randomly after the server ran for 10 minutes or something?

**Comment by darmie** [comment]
> Does it happen all the time or only sometimes? You said that
> 
> > I keep getting a very very slow start whenever my server restarts or is redeployed
> 
> So is it correct that it only happens at the beginning of running the code? Not randomly after the server ran for 10 minutes or something?

It was random, and now it's almost all the time...

**Comment by darmie** [comment]
I use CloudSQL and my database instance is fine, but it seems Prisma can't reach it anymore, and I didn't change the database configurations... 

I get this randomly
```json
{
  "errors": [
    {
      "message": "Could not find user of id 1",
      "path": [
        "user"
      ]
    }
  ],
  "data": {
    "user": null
  }
}
```

**Comment by steebchen** [comment]
Where's your database hosted? Can you confirm it only happened with the current version? If you downgrade now, do you not see the timeouts anymore?

**Comment by darmie** [comment]
@steebchen https://github.com/prisma/prisma-client-go/issues/227#issuecomment-685047300

**Comment by darmie** [comment]
Now I get this...

```json
{
  "errors": [
    {
      "message": "ErrNotFound",
      "path": [
        "user",
        "deliveryAddresses"
      ]
    }
  ],
  "data": {
    "user": null
  }
}
```

**Comment by steebchen** [comment]
That's not a timeout though, that means the record is not found.

**Comment by darmie** [comment]
> That's not a timeout though, that means the record is not found.

That is because of Prisma's inconsistent state. The record exists

**Comment by steebchen** [comment]
Are you sure you're even using this repository? There is no go client v0.11.3 in this repository...

**Comment by steebchen** [comment]
> go client version: v0.11.3

There is no version v0.11.3 of this repository.

**Comment by darmie** [comment]
> > go client version: v0.11.3
> 
> There is no version v0.11.3 of this repository.

Apologies, I ran the wrong command:
Here it is:

```
$ go run github.com/prisma/prisma-client-go version     
Environment variables loaded from current directory
@prisma/cli          : 2.0.0-alpha.1265
Current platform     : darwin
Query Engine         : query-engine 4dbefe724ae6df3621eb660a5d0e0402e34189bf (at /Volumes/Vibranium/Users/damilare/Library/Caches/prisma/binaries/cli/2.0.0-alpha.1265/prisma-query-engine-darwin, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 4dbefe724ae6df3621eb660a5d0e0402e34189bf (at /Volumes/Vibranium/Users/damilare/Library/Caches/prisma/binaries/cli/2.0.0-alpha.1265/prisma-migration-engine-darwin, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 4dbefe724ae6df3621eb660a5d0e0402e34189bf (at /Volumes/Vibranium/Users/damilare/Library/Caches/prisma/binaries/cli/2.0.0-alpha.1265/prisma-introspection-engine-darwin, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 4dbefe724ae6df3621eb660a5d0e0402e34189bf (at /Volumes/Vibranium/Users/damilare/Library/Caches/prisma/binaries/cli/2.0.0-alpha.1265/prisma-prisma-fmt-darwin, resolved by PRISMA_FMT_BINARY)
```

**Comment by steebchen** [comment]
Thanks, much better.

One thing I can recommend is trying to upgrade the go client itself. I have recently published v0.0.6 which is on stable @prisma/cli@2.0.0, which maybe fixes the errors you're getting.

**Comment by darmie** [comment]
@steebchen  I just upgraded and now I get this error 

`2020-09-01 19:45:36.227 WAT2020/09/01 18:45:36 Could not connect to Database: ensure: no binary found`

**Comment by steebchen** [comment]
Can you please remove the `output` and `package` fields? Unfortunately the old values don't work anymore.

**Comment by darmie** [comment]
@steebchen after adjusting my code base accordingly, I have issues deploying my code in Docker

```
 panic: could not run [-v]: fork/exec /root/.cache/prisma/binaries/cli/2.0.0/prisma-cli-linux: no such file or directory
```

This is my DockerFile
```Dockerfile
FROM golang:alpine3.11


ARG DATABASE_URL
ARG JWT_SECRET
ARG OTP_SECRET

COPY . /app

WORKDIR /app

ENV PORT 8080
ENV DATABASE_URL ${DATABASE_URL}
ENV JWT_SECRET ${JWT_SECRET}
ENV OTP_SECRET ${OTP_SECRET}

RUN apk add --update npm bash
RUN npm install -g forever
RUN forever --version
RUN cd geo && npm i 

RUN go get ./...
ENV GOOS linux
ENV CGO_ENABLED 1
RUN go get github.com/prisma/prisma-client-go
RUN go run github.com/prisma/prisma-client-go prefetch
RUN go run github.com/99designs/gqlgen generate
RUN go build -o core server.go

EXPOSE 8080
ENTRYPOINT [ "./core" ]
```

**Comment by darmie** [comment]
@steebchen I did this and still getting no binary found
```prisma
generator db {
  provider = "go run github.com/prisma/prisma-client-go"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

`Could not connect to Database: ensure: no binary found`

**Comment by steebchen** [comment]
Can you try adding `go run github.com/prisma/prisma-client-go prefetch` after the prefetch step?

**Comment by darmie** [comment]
> Can you try adding `go run github.com/prisma/prisma-client-go prefetch` after the prefetch step?

I thought I already did

**Comment by steebchen** [comment]
(sorry, edited that..)

**Comment by darmie** [comment]
@steebchen oh okay, I have spotted that error before and changed it.

It works now... after meddling with Dockerfile for hours...

I still get a delay when calling nested GraphQL queries.... which makes me worry.. but everything seems fine for now

**Comment by steebchen** [comment]
Glad to hear that

**Comment by darmie** [comment]
@steebchen sadly the problem persists... Prisma seems to be having multiple restarts... 

![Screenshot 2020-09-02 at 12 04 42](https://user-images.githubusercontent.com/848002/91973836-cd6fb380-ed14-11ea-8d4b-c9ff545c6b90.png)

![Screenshot 2020-09-02 at 12 03 19](https://user-images.githubusercontent.com/848002/91973599-694cef80-ed14-11ea-99eb-170cf16e71e6.png)

**Comment by darmie** [comment]
I have found the problem to be from a background service that was terminating the server.... thereby making it to restart over and over... 

Thanks for your time so far, you have been helpful
