### ISSUE TITLE
Database Transactions?

### ISSUE THREAD

**Issue by hugbubby** [prisma/prisma-client-go#237]
Sometimes a series of mutation queries need to all succeed at once, or else rollback. I don't see anything about this in the issues or in the documentation so I'm assuming it's an unsupported feature.

The gorm library handles transactions (I think) pretty well. Pseudocode for a transaction mechanism is prisma could look like this, using a closure to handle rolling back or committing the changes made:

```
err := pclient.NewTransaction(func(client PrismaClient) error {
     if users, err := client....; err != nil {
        return err //non-nil err, so Prisma attempts to rollback the transaction; no mutation actions are actually commtted to the database
     }
     ...
     return nil //nil err, so Prisma attempts to commit everything; if this fails, all actions are rolled back.
})
```

In my case, the apps that use Prisma follow the "crash-only" principle and have to stay functional despite not knowing when they are going to be restarted or killed, and that's really cumbersome to do safely without database transactions. ATM prisma's migration and code generation is so useful that we're just going to have to deal by manually cleaning up each unfinished chain of mutations upon restart and unexpected error, but this is almost necessary for real world use cases.

**Comment by steebchen** [comment]
It's supported by Prisma and the [js client](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/transactions), but not in the go client yet due to constrained resources. It also has [some limitations](https://www.prisma.io/docs/more/limitations#long-running-transactions).

**Comment by robojones** [comment]
Transactions would be a valuable addition to the client but I think it is important that the transaction API fits to the existing structure of the client.

```golang
// Create the queries we want to execute.
// Note that we are calling .Tx() instead of .Exec() on the queries.
// The .Tx() call returns a pointer which we can use to get the result.
postTx := client.Post.Create(…).Tx()
stuffTx := client.Stuff.Update(…).Tx()

// Aggregate the different queries into a single transaction, then execute both queries.
// If on of the queries in the transaction fails, all changes are rolled back.
tx := db.Transaction(postTx, stuffTx)
err := tx.Exec(ctx)
if err != nil {
  panic("Transaction failed. Database not modified.")
}

// Use the channels to receive the result of the queries.
post := <- postTx
stuff := <- stuffTx
print(post.Title())

// Alternative approach without channels
post := postTx.Result()
stuff := stuffTx.Result()
print(post.Title())
```

**Comment by steebchen** [comment]
We need to differentiate between simple transactions and what Prisma calls "long running transactions". To read more about what this exactly means, please see https://www.prisma.io/docs/about/limitations#long-running-transactions and https://www.prisma.io/blog/how-prisma-supports-transactions-x45s1d5l0ww1.

For long running transactions, please note that we currently don't have plans to implement this. However, a possible syntax could look as follows:

```go
tx, err := db.Tx()
if err != nil {
  return tx.Rollback()
}
user, err := client.User.CreateOne(...)
if err != nil {
  return tx.Rollback()
}
post, err := client.Post.CreateOne(user.ID, ...)
if err != nil {
  return tx.Rollback()
}
log.Printf("post: %+v", post)
return tx.Commit()
```

However, as I said, we currently don't have plans to implement long running transactions. 

A simple transaction API for unrelated write operations, which is already available in the Prisma JS client, could look as follows:

```go
write1 := client.User.CreateOne()
write2 := client.Post.CreateOne()
write3 := client.Profile.CreateOne()
client.Transaction(write1, write2, write3)
```

**Comment by steebchen** [comment]
For now, we'll implement basic transactions which won't return anything. This is similar to what the JS client transaction API does at this point.

The syntax will look something like I mentioned above:

```
write1 := client.User.CreateOne(...)
write2 := client.Post.CreateOne(...)
write3 := client.Profile.CreateOne(...)
err := client.Transaction(write1, write2, write3)
```

The limitation is that `write1` just holds the information about what to write, and does not return any data. It gets sent to the database at once at `client.Transaction` and does not return anything except for a potential error.

**Comment by steebchen** [comment]
There's also another problem. Since `client` will contain fields which act as a namespace for each Prisma schema field defined, this will clash for models which have a model named "Transaction". In the JS client, we use $ prefixes, such as `prisma.$transaction(...)`, but this is not possible in Go.

We'll need to think of something else. One solution might be to introduce a `Prisma` namespaces, so that you would invoke `client.Prisma.Transaction(...)` and could use `client.Transaction` for a model called `Transaction`.
