### ISSUE TITLE
Dedicated documentation site

### ISSUE THREAD

**Issue by dangdennis** [prisma/prisma-client-go#250]
First off, ~1-2 weeks with prisma, and I've grown quite fond of it. The prisma devs working on this client are doing fantastic work. Huge potential.

Are there any plans to move the current docs to a dedicated doc website? Or perhaps just more guidance on how you'd like to lay out the docs in the repo's README. I'd love to contribute some writing.

As a first time Prisma user, it was quite confusing to learn how to build basic joins, etc. It wasn't immediately clear what the general patterns were: how you'd form joins, how to do basic queries, subqueries, etc. Fortunately an advanced guide exists now! I wish it was written sooner. It would've helped with my early pains. 

Potentially helpful guide: 
- A quick blurb to explain the generated types for relationships. 
- Explanations for general methods: Set, SetOptional, Link, With, etc. So at a high level, devs can understand the beaten path, on top of reading the examples.

**Comment by steebchen** [comment]
Thanks for the kind words! We'd like to integrate docs into prisma.io/docs but the go client has limited resources at this time, which is why we're keeping the docs in the repository for now. However, I'm happy to say that I am currently working on updating the documentation with all the query capabilities, the new quickstart and the advanced quickstart is just the start. We'll also add documentation of generated types, that's definitely a good idea.

**Comment by dangdennis** [comment]
> Thanks for the kind words! We'd like to integrate docs into prisma.io/docs but the go client has limited resources at this time, which is why we're keeping the docs in the repository for now. However, I'm happy to say that I am currently working on updating the documentation with all the query capabilities, the new quickstart and the advanced quickstart is just the start. We'll also add documentation of generated types, that's definitely a good idea.

Great to hear you're writing more docs! Thank you @steebchen 

If I may add, a list of missing features compared to the JS client will also be very helpful to allow others to quickly assess their use case.

Fortunately for me, my SQLs are pretty simple atm.

**Comment by steebchen** [comment]
related: https://github.com/prisma/docs/issues/1069
