### ISSUE TITLE
ensure: no binary found

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma-client-go#256]
Noticed there was some plan for documentation of this error!

https://github.com/prisma/prisma-client-go/blob/b9cc5909b677c122bcb6a771ef179bff40aa1ef7/engine/lifecycle.go#L118

I'm on Windows so I assume that's the issue. I generated the code using Docker because the latest version doesn't support Windows!

**Comment by steebchen** [comment]
This comment might actually be outdated.

> I generated the code using Docker because the latest version doesn't support Windows!

Could you elaborate?
Can you try using v0.0.8 which should still support windows?

**Comment by Southclaws** [comment]
Yeah I'm doing that now and it works fine!

I didn't know about the new code generation stuff (`query-engine-debian-openssl-1.1.x_gen`) so I thought I could just spin up Docker to generate the Prisma code!

It's running fine now though, I'll wait for Windows support upstream before updating 👍

**Comment by steebchen** [comment]
Cool! You don't need docker though, do you?

**Comment by steebchen** [comment]
A general note: when you encounter the `ensure: no binary found` error, it's probably best to re-run `go run github.com/prisma/prisma-client-go generate` to make sure you have the correct generated code.

**Comment by Southclaws** [comment]
I couldn't run the generator on Windows for the latest version so that's why I used Docker.

But for now I just cloned, checked out and built from source to make sure I had the right one - it's all running smoothly now!
