### ISSUE TITLE
Link hasMany on create

### ISSUE THREAD

**Issue by jemilezzet** [prisma/prisma-client-go#285]
I would like to link many records to a record on create. In the following example, an `actionItem` `hasMany` `assignee`.

```
assigneeIDs = []string

primsa.ActionItem.CreateOne(
	prisma.ActionItem.Assignees.Link
		prisma.User.ID.In(assigneeIDs),
	),
)
```

**Comment by steebchen** [comment]
Thanks, `Link` currently only works with one to one relations. It was unintended, but we need some new syntax to be able to link multiple events.

**Comment by steebchen** [comment]
Actually, you can just do this:

```go
created, err := client.User.CreateOne(
	User.Email.Set("new"),
	User.Username.Set("new"),
	User.ID.Set("new"),
	User.Posts.Link(
		Post.ID.Equals("a"),
		Post.ID.Equals("b"),
	),
).Exec(ctx)
```

Since there can be only one argument to link fields, you can just provide those using the variadic function parameters.

**Comment by steebchen** [comment]
The solution provided in #288 allows you to write many links in a .Link:

```go
created, err := client.User.CreateOne(
	User.Email.Set("new"),
	User.Username.Set("new"),
	User.ID.Set("new"),
	User.Posts.Link(
		Post.ID.Equals("a"),
		Post.ID.Equals("b"),
	),
).Exec(ctx)
```

**Comment by steebchen** [comment]
You can now run `go get github.com/prisma/prisma-client-go@master` to make use of this feature.

**Comment by jemilezzet** [comment]
Great! Thanks for the quick turnaround on this.
