### ISSUE TITLE
FindOne by model ID and owner ID

### ISSUE THREAD

**Issue by hi019** [prisma/prisma-client-go#287]
I have this schema:

```graphql
model Collection {
    id     String @id @default(cuid())
    name   String
    Feeds  Feed[]
    userID String
    user   User   @relation(fields: [userID], references: [id])
}
```

I want to query for a single collection with an ID and a user ID. This works:

```go
h.DB.Collection.FindOne(
	db.Collection.ID.Equals(colID),
).Exec(context.TODO())
```

But when I add `db.Collection.UserID.Equals(colID)` I get 

```
too many arguments in call to h.DB.Collection.FindOne
        have (db.collectionWithPrismaIDEqualsParamsUnique, db.collectionWithPrismaUserIDEqualsParams)
        want (db.iCollectionEqualsParamsUnique)
```

```go
h.DB.Collection.FindOne(
	db.Collection.ID.Equals(colID),
	db.Collection.UserID.Equals(userID),
).Exec(context.TODO())
```

**Comment by steebchen** [comment]
You can only query for records which are guaranteed to be unique in Prisma's FindOne. You will either need to define a unique index on the `userID` field (which I don't think would make too much sense), or use `FindMany` (or soon `FindFirst`).

**Comment by hi019** [comment]
Makes sense. Thanks!

**Comment by steebchen** [comment]
BTW, we'll soon introduce `FindFirst`, which acts like `FindMany` but returns the fist record only. It's tracked in https://github.com/prisma/prisma-client-go/issues/303.
