### ISSUE TITLE
Prisma Migrate Up Command Error

### ISSUE THREAD

**Issue by quavious** [prisma/prisma-client-go#294]
First, I have defined schema.prisma file and mariadb database model.  
Because prisma-go library does not execute the command "prisma introspect", which is able to be executed in JS, and TS.  
```
datasource db {
    provider = "mysql"
    url = "mysql://DB_USERNAME:DB_PASSWORD@localhost:PORT_NUMBER/DATABASE_NAME"
}

generator db {
    provider = "go run github.com/prisma/prisma-client-go"
}

model author {
  id      Int      @id @default(autoincrement())
  name    String?
  email   String   @unique
  posts    post[]
  profile profile?
}

model post {
  id        Int      @id @default(autoincrement())
  title     String
  createdAt DateTime @default(now())
  content   String?
  published Boolean  @default(false)
  authorId  Int
  author    author   @relation(fields: [authorId], references: [id])

  @@index([authorId], name: "authorId")
}

model profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  userId Int     @unique
  author author  @relation(fields: [userId], references: [id])
}
```  

And i inputed two commands, as i look in getting started page, in powershell.  

```
go run github.com/prisma/prisma-client-go migrate save --experimental --create-db --name "NAME"
go run github.com/prisma/prisma-client-go migrate up --experimental
``` 

DB connection was good, and then the command "migrate save" is executed with no errors.  
But i encountered this error when i entered "migrate up" command.  
```
Error: P1014
The underlying table for model `_migration` does not exist.
panic: could not run [migrate up --experimental]: exit status 1
goroutine 1 [running] ...
```
What is the problem that the command "migrate up" did not working?

**Comment by steebchen** [comment]
Can you try upgrading the go client to the `master` version using `go get github.com/prisma/prisma-client-go@master` and re-running? If the issue still persists, please comment here, and I'll transfer the issue to https://github.com/prisma/migrate.

**Comment by steebchen** [comment]
Closing for now, please re-open if you should still have issues.
