### ISSUE TITLE
Native types

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#299]
umbrella issue for native types

- [x] BigInt #437
- [x] Decimal #420 
- [x] Bytes #439

**Comment by matthewmueller** [comment]
We're currently missing support for the `@<nativetype>` variants: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default-type-mappings

I'm not sure if you want to create separate issues or just turn this one issue into an epic.

**Comment by steebchen** [comment]
This is actually already supported. See this test: https://github.com/prisma/prisma-client-go/blob/master/test/types/native/schema.prisma

I probably should have clarified before closing, but yeah, they're supported.
