### ISSUE TITLE
Generated package: single vs multiple packages

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#3]
There are two major ways to generate the photon client. It could be generated into a single file, but it could also be generated into separate packages, i.e. a photon package plus one package per model.

### 1) Single File

The client will be generated in a single file, e.g. `prisma/photon_gen.go`.
This is a simple approach where you can access anything photon-related by importing `"photon"`.

##### Example directory structure

```
prisma/
  photon_gen.go
main.go
```

##### Example

```go
import (
  "github.com/org/repo/photon"
)

func main() {
  client := photon.New()
  
  user, err := client.User.FindOne(
    photon.User.Email.Equals("hi@prisma.io"),
  )
}
```

#### Notes

- Very simple approach. One file contains everything you need.
- You can simply use a "." import if you don't want to type "photon." all time
- since `User` is already used for the User query builder, it clashes with the actual User result struct which now has to be named `UserObject` or `UserResult`

### 2) Multiple packages

The client will be generated in multiple files.

##### Example directory structure

```
photon/
  client.go
  tx.go
  user/
    user.go
  user_query.go
  group.go
main.go
```

```
...
photon/
  photon_gen.go
  user/
    user_gen.go
  post/
    post_gen.go
```

The `photon` package contains the basic API to call CRUD functions like FindOne, Update, Delete, etc., as well as helper methods for nullability or common enums such as `Order.ASC`.

The model packages contain the mapped Go struct and all related query functions.

##### Example

```go
import (
  "github.com/org/repo/photon"
  "github.com/org/repo/user"
)

func main() {
  // the photon package contains common structs and functions
  client := photon.New()
  
  usr, err := client.User.FindOne(
    // since this is a query for the user model, we can use the user package here
    user.Email.Equals("hi@prisma.io"),
  )
}
```

This makes the API slightly cleaner because you can access model-specific query functions.

#### Notes
- It results in typing fewer chars (typing `user.` instead of `photon.User`), but you can just use dot imports for the photon package and save yourself the trouble of multiple packages.

#### Caveats with multiple packages

There are many drawbacks of having multiple packages:

- **The `user` package clashes with the usual variable name `user`, which forces you to name it differently, for example `usr`. That is against the philosophy of Go: don’t use package names which clash with common variable names.**
- Multiple imports. Users may get confused about many packages and when to use which. If it's a single package, they can just type `photon.` and get editor completions on what they can type.
- Common practice. Other code generators, let it be google/wire or 99designs/gqlgen, always output to a single file because codegen always works like “helpers” or “additional code”.
- What if a model gets deleted? The user would have to clean it up manually*

*We could solve that by re-creating the `photon/` folder from scratch each time, but this would mean it would be isolated from any other code. This would mean we would have to delete the directory, which may result in confusing and unwanted behavior, like file system issues (recursively deleting files, accidentally deleting /) or accidentally deleting user code. This also means that users could not add anything to the photon package, which some users may want. For example, you may want to extend a User type to an Admin and Moderator type, and then you could add your own functions in your own user.go file in the same `photon` package. See #4 for more information as this is closely related.

Related:
- [photon code mutability](#4)
- [gqlgen: Split generated stubs into multiple files](https://github.com/99designs/gqlgen/issues/377)
- [ent go](https://entgo.io/docs/code-gen/) generates multiple packages, but does not re-create everything from scratch

**Comment by robojones** [comment]
I prefer having all the generated code in a singe file.
I use [wire](https://github.com/google/wire) for dependency injection which means that I need to have a provider function which returns the completely configured prisma client.
```go
func NewClient() *Client {
  return New(&Config{
    Endpoint: "..."
    Secret: "..."
    // ...
  })
}
```
With the Prisma 1 Client I would always put this provider function in the same package along with the generated client. I would like being able to do that with the new client as well.

**Comment by steebchen** [comment]
For now, we have decided to use a single package for the reasons listed in the original issue.
