### ISSUE TITLE
Introduce `FindFirst`

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#303]
FindFirst behaves like FindMany, but sets `LIMIT 1` and returns a single item. The difference to FindOne is that FindOne only allows query which are guaranteed by the database to be unique, such as primary keys or fields marked with @unique.

One big question we need to answer for FindFirst is how it behaves when no item is found. FindOne returns an error if no item is found, while FindMany returns a nil slice. Since this method will return a struct, it's unclear what the best option is here.

I'd probably say the best way to do this is to just return an `ErrNotFound` error was well if no record is found.

**Comment by hi019** [comment]
> I'd probably say the best way to do this is to just return an ErrNotFound error was well if no record is found.
Agreed, and it's in line with the rest of the query error handling.

**Comment by steebchen** [comment]
We could implement this right now, but refactoring internals via #150 but it could take a while.
