### ISSUE TITLE
How does one scrap the old migration and start from scratch? Prisma seems stuck referencing old deleted db

### ISSUE THREAD

**Issue by adrianocr** [prisma/prisma-client-go#317]
I followed the quickstart guide, verified it worked, then deleted that sqlite db and schema. Created a new one, set the provider to postgres, and ran `go run github.com/prisma/prisma-client-go migrate save --experimental --create-db --name "postgres"` but I keep getting the following error: 

```
Prisma schema loaded from schema.prisma
Error: There are more migrations in the database than locally. This must not happen.
Local migration ids: (empty).
Remote migration ids: 20201123000439-init, 20201123001901-init
panic: could not run [migrate save --experimental --create-db --name postgres]: exit status 1

goroutine 1 [running]:
main.main()
	/Users/xxxxxxxxxxxxx/.go/pkg/mod/github.com/prisma/prisma-client-go@v0.1.0/main.go:29 +0x493
exit status 2
```

Seems to me like it is still referencing the old sqlite db, correct? I've searched high and low for a cache directory where prisma may have saved the migration details, I've uninstalled and reinstalled prisma a few times, ran `go clean` with just about every possible flag, and yet I still can't get prisma to forget about the old sqlite.db file and treat it like a new migration.

So how do I get prisma to forget about everything prior to right now and start from scratch?

**Comment by steebchen** [comment]
There are two places where migration information is saved: 1. migration files in the `migration/` or `prisma/migration/` directory, and 2. in the database itself in a `_Migration` table. If you delete both, it should work.

If you are in development and don't need migration files yet, you can also use db push to just get your database in sync with your schema: `go run github.com/prisma/prisma-client-go db push --preview-feature`. I will update the documentation around this command soon.

**Comment by adrianocr** [comment]
@steebchen thanks for the reply!

I figured that was the case but in reality it isn't working like that. No `migrations` directory was created. Is that something I should manually create? But then you say to delete it so I don't see how that would work. Secondly I deleted the entire db file, not just the _Migrations table. So shouldn't that have done the trick? Yet it seems like prisma is still hanging onto the db file or some migrations log somehow despite the fact that I've deleted the entire db _and_ the prisma directory. 

Unless the directory gets created elsewhere not in the project root?

**Comment by adrianocr** [comment]
@steebchen ok so I am not 100% sure what I did but this comment may be helpful for someone in the future or for you guys to tweak the error messages going forward.

Basically it seemed that the above errors were due to the fact that prisma couldn't connect to the postgres server for some reason. Maybe I had the wrong address or wrong password or something but it would not work. When I uninstalled and reinstalled postgres and verified the credentials through PgAdmin I got prisma to work. 

And to fix the sqlite issue I manually created a /migrations/ directory in the prisma directory, created the sqlite.db file, and re-ran the commands. It worked that time around and then when I switched the provider to postgres it also worked correctly.

**Comment by steebchen** [comment]
Thanks for the info. Deleting the file and removing the `migration` directory should do the trick, if that doesn't work it's a bug. However, I would need the exact error message to further help you. In general, if you run migrate with the --create-db command, the sqlite database should be created for you, you don't need to create anything manually. Feel free to re-open should you run into this issue again.

**Comment by steebchen** [comment]
Also, I recommend running `go run github.com/prisma/prisma-client db push --preview-feature` for development – no migrations are created and the database may get reset, but it's the easiest way to sync your database with your prisma schema.
