### ISSUE TITLE
.env file not being loaded at runtime

### ISSUE THREAD

**Issue by hi019** [prisma/prisma-client-go#324]
Hello! I'm getting this error when trying to create a db connection:

```json
{
   "is_panic":false,
   "message":"\u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:3\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 2 | \u001b[0m    provider = \"mysql\"\n\u001b[1;94m 3 | \u001b[0m    url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1",
   "meta":{
      "full_error":"\u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:3\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 2 | \u001b[0m    provider = \"mysql\"\n\u001b[1;94m 3 | \u001b[0m    url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1"
   },
   "error_code":"P1012"
}
```

`DATABASE_URL` is from a .env file at the same level as my schema. I am able to create & run migrations with the `migrate` command. Does the Go client not yet support .env files?

Schema:

```gql
datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
    output   = "prisma-gen"
}

generator db {
    provider = "go run github.com/prisma/prisma-client-go"
    package  = "prisma"
    output   = "prisma"
}

model User {
    id         String  @id @default(cuid())
    email      String  @unique
    password   String
    isVerified Boolean
}

**Comment by hi019** [comment]
Fixed by using https://github.com/joho/godotenv. Should this be noted in the docs?

**Comment by steebchen** [comment]
Can you please describe exactly where your prisma.schema and .env folder are? Are they both in your root project directory?

**Comment by steebchen** [comment]
I think the default behaviour of Prisma is to expect the schema in a folder called `prisma`, so it'd be best to do that (so the schema location is `prisma/schema.prisma`.

I've updated the documentation to recommend that per default via https://github.com/prisma/prisma-client-go/pull/335.

Closing for now – if something is still wrong, please re-open.

**Comment by hi019** [comment]
Apologies for my late response. My folder structure looks like this:

```
├── api
│   ├── ...
├── constants
│   └── ...
├── migrate.sh
├── migrations
│   ├── ...
├── prisma
│   ├── db_gen.go
│   ├── query-engine-debian-openssl-1.1.x_gen.go
│   └── query-engine-linux_gen.go
├── schema.prisma
├── services
│   ├── ...
└── user
    ├── ...

```

It's all inside a directory called `internal`. I assume the `prisma` folder confuses the client.

**Comment by steebchen** [comment]
Ah ok, I misunderstood at first. Basically the Go client does not read .env files yet, so we would need to add this.

**Comment by paulm17** [comment]
The fix for using godotenv really needs to be in the quickstart.  I tried using a connection string and kept on getting:

```
{"is_panic":false,"message":"The provided database string is invalid. Error parsing connection string: invalid port number in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.","meta":{"details":"Error parsing connection string: invalid port number in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters."},"error_code":"P1013"}
```

**Comment by steebchen** [comment]
Got it @paulm17, I'll make sure to raise it internally and either document it or just use godoenv internally.

**Comment by steebchen** [comment]
This is now implemented, but only resolves the .env file in some directories. I created a [follow-up issue](https://github.com/prisma/prisma-client-go/issues/495), so that an .env file is resolved where the schema.prisma file is.

**Comment by matthewmueller** [comment]
Which directories does it currently resolve in? The directory with go.mod?

**Comment by steebchen** [comment]
Yes, the root directory, but it also checks `db/` and `prisma/`
