### ISSUE TITLE
There seems to be an issue with the JSON type code gen, along with inserting into postgres

### ISSUE THREAD

**Issue by adrianocr** [prisma/prisma-client-go#326]
Give the following schema:

```
model Config {
    id                      String          @default(cuid()) @id
	object                  String
	fields                  Json
	storeInstance           StoreInstance   @relation(fields: [storeInstanceID], references: [id])
	storeInstanceID         String
}
```

and the following two commands:

`go run github.com/prisma/prisma-client-go db push --preview-feature && go run github.com/prisma/prisma-client-go generate`

I get an issue where `db_gen.go` is missing a proper type for the JSON type. 

```console
prisma/db/db_gen.go:6732:14: undefined: JSON
prisma/db/db_gen.go:6741:38: undefined: JSON
prisma/db/db_gen.go:9751:42: undefined: JSON
prisma/db/db_gen.go:9763:51: undefined: JSON
prisma/db/db_gen.go:9766:10: undefined: JSON
prisma/db/db_gen.go:9778:45: undefined: JSON
prisma/db/db_gen.go:9792:44: undefined: JSON
prisma/db/db_gen.go:9813:54: undefined: JSON
```

The solution is to go into `db_gen.go` and insert a custom type at the top, `type JSON json.RawMessage` and the issue goes away.

---

Additionally it seems that the Json type in the prisma config is handled as "jsonb" in postgres, which is ideal, but postgres seems to want to receive the data as a plain string but prisma is handling json like a byte slice? If I override the Json type to be a string I can insert data into postgres just fine. But if I leave it as a rawmessage/byte slice postgres complains about the following:

```console
pql error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "createOneConfig", "data", "ConfigCreateInput", "fields"] }, error_kind: ValueParseError("Invalid json: expected value at line 1 column 1") })
```

**Comment by steebchen** [comment]
Hey, can you try upgrading to the latest version by running `go get github.com/prisma/prisma-client-go@master` and then re-generate. JSON support is already there, I just didn't release it via a GitHub tag yet.
