### ISSUE TITLE
The method updateOne returns FieldNotFoundError.

### ISSUE THREAD

**Issue by quavious** [prisma/prisma-client-go#345]
I am working with Echo, the web framework, MariaDB, and Prisma 2.  
Exercising CRUD simple posts, I encountered the problem when i update one post.  

I have let route "post/:id", which makes the post be updated. And uri parameter is id, such as 1, 2, 3  
In Echo framework, uri parameters can be accessed with c.Param("id").  
I triggered POST request with JSON object which includes title, and description as desc.  
But the terminal said the error  **pql error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "updateOnePost"] }, error_kind: FieldNotFoundError })**. 

I have predicted that if i launch post request to **/posts/3**, then title and content in post with id 3 should be changed, but not.  

I am going to attach Prisma schema code, echo request handler code, and JSON request body.  
I am using MariaDB, not PostgreSQL.  
```
model post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime
  title     String
  published Boolean
  desc      String?
```  

```go
type Post struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}
var client *db.PrismaClient = db.NewClient()
var ctx context.Context

func init() {
	ctx = context.Background()
        if err := client.Connect(); err != nil {
		log.Panicln(err)
	}
}
// UpdatePost Modifies a Post Being Already Created
func UpdatePost(c echo.Context) error {
	p := new(Post)
	if err := c.Bind(p); err != nil {
		log.Println(err.Error())
		return c.JSON(http.StatusBadRequest, echo.Map{
			"status": "fail",
			"msg":    "Server Error",
		})
	}

	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		log.Println(err.Error())
		return c.JSON(http.StatusBadRequest, echo.Map{
			"status": "fail",
			"msg":    "Server Error",
		})
	}

	post, err := client.Post.FindOne(
		db.Post.ID.Equals(id),
	).Update(
		db.Post.UpdatedAt.Set(time.Now()),
		db.Post.Title.Set(p.Title),
		db.Post.Published.Set(true),
		db.Post.Desc.Set(p.Desc),
	).Exec(ctx)
	if err != nil {
		log.Println(err.Error())
		return c.JSON(http.StatusBadRequest, echo.Map{
			"status": "fail",
			"msg":    "Server Error",
		})
	}

	str, err := json.MarshalIndent(post, "", " ")
	if err != nil {
		log.Println(err.Error())
		return c.JSON(http.StatusBadRequest, echo.Map{
			"status": "fail",
			"msg":    "Server Error",
		})
	}
	return c.JSON(http.StatusOK, echo.Map{
		"status":         "OK",
		"content-length": len(str),
		"msg":            "The Post was modified as You Want",
	})
}
```

```JSON
{
    "title" : "Example Title Edited",
    "desc": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}
```
the properties id, and createdAt is not required when creating.  
I have installed prisma-client-go latest version many times, and Echo version is v4.  

What is the problem?

**Comment by steebchen** [comment]
Do you use prisma migrate or introspection? Can you make sure you have either migrated the database or if you use introspection that you have introspected your database, and then after that re-generate your client?

**Comment by quavious** [comment]
> Do you use prisma migrate or introspection? Can you make sure you have either migrated the database or if you use introspection that you have introspected your database, and then after that re-generate your client?

I have used prisma introspect and generate a few times. prigma migrate save & up command caused the error "__migration table does not exist.", so before introspection I created the posts table with HeidiSQL..

**Comment by steebchen** [comment]
It most likely has something to do with migrations. I suggest you to try making sure your prisma schema file is up to date, and then running the new command `go run github.com/prisma/prisma-client-go db push --preview-feature` – it's like migrating but for local development, which just makes sure your database schema is in sync with your schema; ignoring migration files.

**Comment by quavious** [comment]
> It most likely has something to do with migrations. I suggest you to try making sure your prisma schema file is up to date, and then running the new command `go run github.com/prisma/prisma-client-go db push --preview-feature` – it's like migrating but for local development, which just makes sure your database schema is in sync with your schema; ignoring migration files.

Confirmed. I am going to try your advices, and will comment after.

**Comment by quavious** [comment]
```go
found := client.Post.FindOne(
		db.Post.ID.Equals(id),
	)

	post, err := found.Update(
		db.Post.Title.SetIfPresent(&p.Title),
		db.Post.Desc.SetIfPresent(&p.Desc),
	).Exec(ctx)
```

I have deleted the table being already created, and created new table with same properties.
**"__migration table is not exist" error**  is caused at this time, So i have introspect and generate again.
It was also confirmed Prisma schema file was normally generated.  

I seperated one update code to two parts, 1) find a row by id, 2) update rows with new title, and desc that match this id.  
The id was 1. So it's update route became **/posts/1**.  
Printing found.Exec(ctx) presented the message.  
**{{1 2020-12-14 17:25:02 +0000 +0000 2020-12-14 17:25:02 +0000 +0000 ADDRESS ADDRESS ADDRESS} {}}**  
The time when i executed this POST request was after the created Time, 2020-12-14 17:25:02.  

It was seem that the code found the row according the id number, but update code caused the same error.  
I would dare to tell prisma developers that Update Method has somewhat error.  

I don't know what happened internally...  
Thank for your services..

**Comment by steebchen** [comment]
So does it still not work or is this considered resolved?

**Comment by quavious** [comment]
> So does it still not work or is this considered resolved?

findOne and update function is still not working..

**Comment by steebchen** [comment]
I can't reproduce. Can you please provide a full reproduction, including the schema and some code which fails which I can run on my machine to reproduce?

**Comment by quavious** [comment]
When i replace mariadb with postgreSQL, the update method could be executed normally.
PostgreSQL database seems to be more harmonious with Prisma Client Go.
My Problem is now solved. Can i close this issue?

**Comment by steebchen** [comment]
Yeah, I'll go ahead and close since it looks like it's not related to the go client. If it is feel free to re-open.
