### ISSUE TITLE
Transactions should return results

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#363]
Transaction were implemented via https://github.com/prisma/prisma-client-go/issues/237, but they currently can't return anything. Since we can't infer the return type of the input values of the `Prisma.Transaction` method, we need to come up with something else.

**Comment by steebchen** [comment]
syntax proposal: 

```go
			createUserA, a := client.User.CreateOne(
				User.Email.Set("a"),
				User.ID.Set("a"),
			).Tx()

			createUserB, b := client.User.CreateOne(
				User.Email.Set("b"),
				User.ID.Set("b"),
			).Tx()

			if err := client.Prisma.Transaction(createUserA, createUserB).Exec(ctx); err != nil {
				t.Fatal(err)
			}

			time.Sleep(5 * time.Second)

			expectedA := &UserModel{
				InnerUser: InnerUser{
					ID:    "a",
					Email: "a",
				},
			}

			expectedB := &UserModel{
				InnerUser: InnerUser{
					ID:    "b",
					Email: "b",
				},
			}

			assert.Equal(t, expectedA, <-a)
			assert.Equal(t, expectedB, <-b)
```

**Comment by matthewmueller** [comment]
I slightly prefer the second one because:

1. `.Result()` can return the same thing every time, as opposed to panicking or hanging
2. Less variables `createUserA :=` instead of `createUserA, a :=`

**Comment by matthewmueller** [comment]
From slack discussions:

> could be more obvious that it has something to do with transactions, as .Result() could be misleading when you actually want to use Exec()

Maybe `CreateOneTx`?

**Comment by steebchen** [comment]
No, it should a separate method, otherwise it will make codegen harder, and I also think it's slightly cleaner to just put a .Tx() after a method once you want to run it in a transaction.

**Comment by matthewmueller** [comment]
That sounds good then. I think you're right that just having Result() attached to everything could be confusing.
