### ISSUE TITLE
partial update without null or zero value

### ISSUE THREAD

**Issue by uta-mori** [prisma/prisma-client-go#364]
When a field has a null or zero value, I want to remove the part that updates that column from the generated UPDATE statement.

in `prisma-client-js`, this seems to be accomplished with ternary operator and `undefined`

Can I do this with `prisma-client-go` ?

[Null and undefined (Reference) | Prisma Docs](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined)

```js
const update = await prisma.user.update({
  where: {
    id: 1,
  },
  data: {
    name: "Petunia",
   email: emailInput != null ? emailInput : undefined, // If null, don't include in update!
  },
});
```

Setting a field value to undefined is the same as not including the email property in the update query at all:

```js
const update = await prisma.user.update({
  where: {
    id: 1,
  },
  data: {
    name: "Petunia",
 // No email update here...
  },
});
```

**Comment by steebchen** [comment]
You can use the SetIfPresent method, such as `User.Email.SetIfPresent(newEmail)`. If `newEmail` is `nil` (since it's a pointer), nothing will be updated; if it's non-nil the value will be updated.

For more information see:
https://github.com/prisma/prisma-client-go/blob/master/docs/reference/14-if-present-methods.md

**Comment by uta-mori** [comment]
Thank you! 😍 
That's just what I was looking for. :bow:

**Comment by Yvad60** [comment]
> https://github.com/prisma/prisma-client-go/blob/master/docs/reference

For anyone just looking the updated link is 
https://github.com/prisma/prisma-client-go/blob/main/docs/reference/16-if-present-methods.md
