### ISSUE TITLE
Generated code mutability

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#4]
The generated photon client can be a single output file which can live anywhere in the repository or a dedicated folder `photon/`, which may get deleted and re-created from scratch on each code generation.

### 1) Immutable photon directory

This will put everything photon-related into the `photon/` directory, and the user is not allowed to edit anything in this directory. This prevents mixing user code with generated code.

Major caveats:
- You would have to generate a single, immutable/read-only directory, and you’d have to/re-create the package each time. This means we would have to delete the directory, which may result in confusing and unwanted behavior, like file system issues (recursively deleting files, accidentally deleting /) or accidentally deleting user code. This also means that users could not add anything to the photon package, which some users may want. For example, you may want to extend a User type to an Admin and Moderator type, and then you could add your own functions in your own user.go file in the same `photon` package, which would make it _impossible_ to add custom code which may result in inconvenience. *

* Note: There was a suggestion to just add "plugins" or functionality to programmatically add custom code which lives somewhere else can be added to the configuration, which could also result in auto-generated code on, for example, each model struct. However, we're far away from a plugin system or custom code generators, and it also adds a lot of complexity to the whole photon go library complex and you'll have “magic” code which may be hard for beginners.

### 2) Individual generated file

This will generate a single file in a given package, e.g. `photon/photon_gen.go`. However, you can also add your own go files into the `photon` package to extend photons functionality.
 
**Useful custom code ideas:**
- helper methods
- extend a User model to Admin and Moderator models
- attach methods to photon model structs to satisfy interfaces
- custom constructors or wrappers
- writing providers for dependency injection

Related: [single vs multiple packages](https://github.com/prisma/photongo/issues/3) (edit: fixed link)

**Comment by darioielardi** [comment]
I'd keep the possibility to add custom code to the package, since it doesn't seem to have any disadvantages.

**Comment by robojones** [comment]
I agree with @darioielardi and propose to close this issue until #3 is decided, since this issue is entirely dependent on #3.

If it is decided to output everything into a **single file**, then it wouldn't make sense to make the directory immutable.

If the decision is to organize the output in **multiple sub-packages**, then they (the directories) must be read-only.
Lest you want to end up with weird issues where someone deleted something from the schema but on your computer the generated code still exists - even after repeatedly regenerating the library. Then you use it in the code and end up with strange "works on my machine" scenarios.

**Comment by steebchen** [comment]
@robojones is right, this depends on #3. I'll still keep this open until we have a decision for #3, and then I'll add the findings here for future readers.

**Comment by steebchen** [comment]
Closed in favour of the decisions in #3.
