### ISSUE TITLE
Support for Decimal columns

### ISSUE THREAD

**Issue by JanPetr** [prisma/prisma-client-go#420]
Hello there! 👋  Today I wanted to add `Decimal` columns to my Postgres DB to store money values. The migration went well, however the client was generated with `Decimal` type, but this one doesn't exist in Go:
```
# github.com/janpetr/net-worth/backend/prisma/db
prisma/db/db_gen.go:9467:14: undefined: Decimal
prisma/db/db_gen.go:9469:14: undefined: Decimal
prisma/db/db_gen.go:9504:11: undefined: Decimal
prisma/db/db_gen.go:11787:47: undefined: Decimal
prisma/db/db_gen.go:11799:57: undefined: Decimal
prisma/db/db_gen.go:11807:50: undefined: Decimal
prisma/db/db_gen.go:11821:60: undefined: Decimal
prisma/db/db_gen.go:11828:49: undefined: Decimal
prisma/db/db_gen.go:11937:50: undefined: Decimal
prisma/db/db_gen.go:11949:60: undefined: Decimal
prisma/db/db_gen.go:11949:60: too many errors
```

![Screenshot 2021-03-03 at 15 24 44](https://user-images.githubusercontent.com/1058144/109819665-9a12d080-7c34-11eb-8e54-7bd15f819fe5.png)

Is the support for `Decimal` type something coming up? Or is there any workaround?

Thank you for your work! 👏

**Comment by steebchen** [comment]
Thanks, yeah, we will need to decide what library (e.g. [this](https://github.com/shopspring/decimal)) to use for decimals, as AFAIK we can't or shouldn't map to float64.

**Comment by JanPetr** [comment]
👍 Yes, thanks! I was about to use the very same library for decimals.

**Comment by steebchen** [comment]
This is now available via `go get github.com/prisma/prisma-client-go@master`.
