### ISSUE TITLE
Incorrect code generated for `BigInt` column

### ISSUE THREAD

**Issue by queer** [prisma/prisma-client-go#437]
Test schema:
```prisma
model Test {
  id Int @id
  test BigInt
}
```

After running `go run github.com/prisma/prisma-client-go db push --preview-feature && go run github.com/prisma/prisma-client-go generate`, the generated Prisma client uses the type `BigInt`, but that type doesn't exist either natively to Go or as an alias. This can be solved by adding `type BigInt = int64` at the end of the generated db client, but this is obviously a suboptimal way of handling the situation.

**Comment by steebchen** [comment]
This is part of a bigger effort of what we call "native types" internally. Hopefully we'll get to it soon. We will also need to decide what library to use for that type.

**Comment by steebchen** [comment]
Should we use big.Int from "math/big" for this?

**Comment by steebchen** [comment]
Should we use big.Int from "math/big" for this? cc @matthewmueller

**Comment by steebchen** [comment]
This is now available via `go get github.com/prisma/prisma-client-go@master`.
