### ISSUE TITLE
Handle nil vs 0 len slices

### ISSUE THREAD

**Issue by tarrencev** [prisma/prisma-client-go#468]
With gqlgen, an array input can be optional. In prisma, I try to set it optionally like

```
prisma.EventInstance.Array.SetIfPresent(&input.Array),
```

But it seems like prisma will set it to a zero length array even if the input value is nil.

Can Prisma differentiate between nil and zero length arrays? My expectation is that the value would not be set in this case.

**Comment by tarrencev** [comment]
@steebchen  do you need more info for this?

**Comment by steebchen** [comment]
Actually, Prisma currently only supports required arrays, and the default value is an empty array.
Also see https://github.com/prisma/prisma/issues/847#issuecomment-683666269
If you want to have optional array fields, please open an issue in https://github.com/prisma/prisma. 

In theory this would be a bug, as SetIfPresent doesn't make a lot of sense if it defaults to an empty array anyway. I'd suggest to handle an empty array as null if that works for your use-case.

I'll close the issue for now as there's nothing I can do for now, but happy to re-open if you feel differently.
