### ISSUE TITLE
Bytes type bug

### ISSUE THREAD

**Issue by OAyomide** [prisma/prisma-client-go#493]
When I tried to create a `Bytes` type, after generating, I ran into an error. The screenshots below show the schema file content and the generated code.

<img width="338" alt="Screenshot 2021-06-05 at 14 05 15" src="https://user-images.githubusercontent.com/26779597/120892598-11c31380-c607-11eb-9e49-ae8f57aa9c78.png">

<img width="465" alt="Screenshot 2021-06-05 at 14 06 34" src="https://user-images.githubusercontent.com/26779597/120892644-4040ee80-c607-11eb-8e34-fe17f13d9198.png">

i was able to track down the issue and fixed it [here](https://github.com/OAyomide/prisma-client-go/commit/0a051228d2d8663b722b051d5b91949ff45e3e70) but I am not sure about how to proceed with making sure the tests pass because I dont (really) know GraphQL. I currently use this in a project so this fix does work I just need help with the test.

[Here](https://github.com/OAyomide/prisma-client-go/blob/f7a94dc08e6643af579aa6fdbed7a34ef9a3ee53/test/databases/postgresql/raw/raw_test.go#L66), I am not sure I understand what it should be as I get parser error. I'd love some help here so I can get this merge and (probably) move on to other issues I am working on.

cc @steebchen i'd appreciate some help here.

**Comment by steebchen** [comment]
Can you be more specific what exactly doesn't work? The implemented tests seem to pass, as `Bytes` refer to `[]bytes` already [here](https://github.com/prisma/prisma-client-go/blob/e2ad98125c4306e14d5b722305986a2dc53ffad3/runtime/types/types.go#L26).

Are you using the latest go client version?


To answer your second question, you could probably just specify a string `"foo"` in the GraphQL setup query.

**Comment by OAyomide** [comment]
Yes, I am using latest go client (v0.9.0)

what doesn't work is that when you specify type "Byte" in the prisma file and generate the go code, it returns "Bytes" (see the first screenshot) which is an invalid type. So i get errors

also, yes, `Bytes` refer to `[]bytes` somewhere in the code but when you run go generate to generate the `db_gen.go` code, it still returns Bytes instead of []byte which is literally the issue I am/was having.

**Comment by steebchen** [comment]
That's weird. I still can't reproduce though. For me, it uses `Bytes`, but in the generated file it's defined as `type Bytes = types.Bytes` (and in package `types`: `type Bytes = []byte`).

Can you please give the exact error message you are getting, and ideally sending the db_gen.go file, as well as your prisma schema to help me reproduce? Thanks.

**Comment by steebchen** [comment]
Please re-open if this still happens with the latest version.
