### ISSUE TITLE
Error updating documents

### ISSUE THREAD

**Issue by zackartz** [prisma/prisma-client-go#497]
Hi! I've been having an issue updating my documents, no matter what I do I get this error 
`pql error: Error in query graph construction: QueryParserError(Q...+112 more`

My Prisma Schema looks like this
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:password@localhost:5432/working?schema=public"
}

generator db {
  provider = "go run github.com/prisma/prisma-client-go"
}

model user {
  id        String        @id @default(uuid())
  username  String        @unique
  password  String
  email     String        @unique
  createdAt DateTime      @default(now())
  updatedAt DateTime      @updatedAt
}
``` 

and the code I am trying to use looks like this:
```go
	user, err := client.User.FindUnique(
		db.User.ID.Equals(u.ID),
	).Update(
		db.User.Username.Set("mock_name"),
		db.User.Email.Set("mock_email"),
		db.User.Password.Set("mock_password"),
	).Exec(ctx)
```

any help would be appreciated!

**Comment by steebchen** [comment]
Hi, this looks correct. I need more information. Can you please share the complete error message, as well as the exact query which is triggering the error? Thanks. Also please specify if you're using the latest go client version.

**Comment by zackartz** [comment]
Hello! 
I am using version 0.9.0 of the client. 

Here is the complete error message:
```
pql error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "updateOneUser"] }, error_kind: FieldNotFoundError })
```

As for what query is triggering the error, I am not sure, the only Prisma code that is running is the one I've previously sent, If there's any thing else I can provide please let me know!

**Comment by zackartz** [comment]
I built [this repo](https://github.com/zackartz/prisma-buggy) that when I run I get this result: 
```
2021/06/13 15:11:30 Created user with ID: 5083e52f-d54f-4627-825b-41cf15dc388d
2021/06/13 15:11:30 An error occured: pql error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "updateOneUser"] }, error_kind: FieldNotFoundError })
panic: An error occured: pql error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "updateOneUser"] }, error_kind: FieldNotFoundError })

goroutine 1 [running]:
log.Panicf(0x100ef663a, 0x14, 0x1400019f578, 0x1, 0x1)
        /opt/homebrew/Cellar/go/1.16.4/libexec/src/log/log.go:361 +0xa8
main.main()
        /Users/zack/Documents/dev/prisma-buggy/main.go:45 +0x7f8
exit status 2
```

Additional info: 
OS - macOS 11.4 (aarch64)
M1 MacBook Pro
Go Version: 1.16.4

**Comment by steebchen** [comment]
Did you make sure to run `go run github.com/prisma/prisma-client-go db push`?

**Comment by zackartz** [comment]
Any updates on this?

**Comment by steebchen** [comment]
Thanks I could reproduce. Will try to fix ASAP.

**Comment by steebchen** [comment]
I got it, it's because the model is called `user`. Try changing it to `User`, e.g. `model User {`. Sorry for the late info, I was on vacation. It's still a pretty bad error so I will fix it soon, thanks for the reproduction.

**Comment by zackartz** [comment]
Ah, that makes sense. I'll use that solution in the mean time. Thank you!
