### ISSUE TITLE
Feature: Mock client

### ISSUE THREAD

**Issue by robojones** [prisma/prisma-client-go#5]
Mocking should be a native feature of the photongo client.

A method using the schema and proposed syntax from #2 could look like this:

```go
func GetUserWithPosts(db photon.Client, ctx context.Context, email string) {
  user, err := db.User.FindOne.Where(
    photon.User.Email.Equals(email),
  ).With(
    photon.User.Posts.Limit(10),
  ).Exec(ctx)

  // Do something with the user and posts
}
```

### Proposal

**My proposal is that photongo generates a mock client** along with the normal client code, which I can use to predefine results for certain queries.
I can then pass the mock client to the method I am testing (e.g. through dependency injection).
Finally the mock should allow me to verify if the specified queries were executed in my code.

Here is how a test for my method above could look like:
```go
func TestGetUserWithPosts(t *testing.T) {
  const testEmail = "hi@prisma.io"

  db, mock := photon.NewMock()

  // Here we define the query which we expect and
  // the result we want to return for this sepecific query.
  mock.Expect.User.FindOne.Where(
    photon.User.Email.Equals(testEmail),
  ).With(
    photon.User.Posts.Limit(10),
  ).Returns(
    // Create the expected result struct here
  )

  // Pass our mocked database to the method.
  GetUserWithPosts(db, context.Background(), testEmail)

  // Check if the correct queries were executed.
  if err := mock.ExpectationsWereMet(); err != nil {
    t.Error(err)
  }
}
```

To return a specific error one can use `.ReturnsError(err)` instead of `.Returns(result)`

This approach is inspired by the [DATA-DOG/go-sqlmock package](https://godoc.org/github.com/DATA-DOG/go-sqlmock) and is essentialy adapting its API approach to work with photongo.

### Implementation

The implementation should be pretty straight forward. We could use the query builder from the actual database client. The mock results can then be stored in a hashmap `map[query] = result/error`.

**Comment by steebchen** [comment]
Thanks for your contribution! This looks promising, and I agree that we should add native mocking very early. I am still busy with the general API specification, but I'll re-visit this when I design the mock API.

**Comment by steebchen** [comment]
Another approach could be an integration mock client, where you can pass models in the constructor function and the user gets a full database-independent in-memory photon client. This would drastically simplify testing. It will also mean more work for the Photon Go team. The GraphQL Apollo Server also provides [these kind of mocks](https://www.apollographql.com/docs/apollo-server/testing/mocking/). It seems this approach would involve a lot of work and has some drawbacks, but I still wanted to suggest it here.

```go
users := []photon.User{{ID: "123", Title: "what up"}}
posts := []photon.Post{{ID: "abc", Name: "John"}}
client := photon.NewIntegrationMockClient(users, posts)
// client is an in-memory Photon Go client without the need for a database
```

Ideally, you would use dependency injection to pass a real client in your normal code and an integration mock client for your tests.

**Caveats**:
- hard to test for errors
- may reduce the quality of tests in general
- more integration than unit tests – a simple docker database setup could be used instead

**Comment by robojones** [comment]
Great idea @steebchen! :+1: 
This would be really simplify testing. Maybe there is a different solution for returning custom errors.
But even if we find a solution for that, I think that this would be really complex to implement. We we would need to support all features of our client: selecting with min, max, equal, joins, ordering,...
Also what about inserts and updates?

We would essentially need to write a complete in-memory database in go.

**Comment by robojones** [comment]
This syntax would allow us to reuse the existing client methods.

```golang
func TestGetUserWithPosts(t *testing.T) {
  const testEmail = "hi@prisma.io"

  db, mock := photon.NewMock()

  // Here we define the query which we expect and
  // the result we want to return for this sepecific query.
  mock.Expect(
    db.User.FindOne.Where(
      photon.User.Email.Equals(testEmail),
    ).With(
      photon.User.Posts.Limit(10),
    )
  ).Returns(
    // Create the expected result struct here
  )

  // Pass our mocked database to the method.
  GetUserWithPosts(db, context.Background(), testEmail)

  // Check if the correct queries were executed.
  if err := mock.ExpectationsWereMet(); err != nil {
    t.Error(err)
  }
}
```

**Comment by steebchen** [comment]
Thank you so much @robojones! I will experiment with this this weekend :)

**Comment by steebchen** [comment]
We could also provide a deferrable method to make sure the expectations were met:

```go
db, mock := photon.NewMock()
defer mock.ExpectationsWereMet(t)
```

Or even returning it directly to make sure the user uses the variable:


```go
db, mock, ensure := photon.NewMock()
defer ensure(t)
```

**Comment by steebchen** [comment]
Mocks can now be type-safe:

```go
db, mock, ensure := NewMock()
defer ensure(t)
mock.User.Expect(
	db.User.FindOne(User.ID.Equals("foo")),
).Returns(expected)
```

Since you will be able to use `mock.<model>.Expect` methods, the struct which is accepted in `Returns` is type-safe.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/5013932/99898681-08f79980-2cd6-11eb-89ea-e568843de0ae.png">
