### ISSUE TITLE
No .Cursor() method on my CreatedAt field

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma-client-go#538]
The docs on order/pagination have an example with `CreatedAt.Cursor(someDate)` here: https://github.com/prisma/prisma-client-go/blob/master/docs/reference/06-order-by.md

but my code doesn't seem to have been generated with a .Cursor method on my CreatedAt field.

Here's the relevant model:

```prisma

model Post {
  id String @id @default(cuid())

  slug    String  @unique
  title   String
  body    String
  short   String
  first   Boolean
  author  User    @relation(fields: [userId], references: [id])
  root    Post?   @relation("PostToRoot", fields: [postId], references: [id])
  posts   Post[]  @relation("PostToRoot")
  replyTo Post?   @relation("ReplyToPost", fields: [postId], references: [id])
  replies Post[]  @relation("ReplyToPost")
  tags    Tag[]   @relation("TagToPost")

  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  deletedAt DateTime?

  userId String
  postId String?
}

model Tag {
  id String @id @default(cuid())

  name  String @unique
  posts Post[] @relation("TagToPost")
}
```

For now I'll just do the old .Take()/.Skip() method but I'd like to use date cursors in future.

Thanks! Also got Prisma in two projects now, one open source and one a B2C product and loving it so far!

**Comment by steebchen** [comment]
I think right now only unique fields expose cursor methods, so if you add an index like `@@index([created_at])` at the bottom of your model, you will be able to use the cursor method.

And thanks for your feedback!

**Comment by Southclaws** [comment]
Ah thanks!

**Comment by steebchen** [comment]
Decided this should be just available everywhere, it's up to the developer if they want to use an index or not.
