### ISSUE TITLE
Batch Transactions

### ISSUE THREAD

**Issue by TheBeachMaster** [prisma/prisma-client-go#539]
Suppose say I have 100 records I want to insert to the DB, the [js doc](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany) [explains](https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-multiple-records) of `createMany`.

Also, there's a mention of [transactions API](https://github.com/prisma/prisma-client-go/blob/master/docs/reference/13-transactions.md). The examples for 2 inserts seems trivial.

In my example it seems very unnecessary to manually write 100 `createOne` statements, so I tried a hack(which failed): here's the pseudocode <- I AM FAIRLY NEW IN GO
```go
vars :=make([]db.statesUniqueTxResult,0) // NOTE that this already fails because statesUniqueTxResult is NOT EXPORTED

// then loop over my data
for _,s := range statesInfo{
m := dbClient.State.CreateOne(...).Tx()
vars =append(vars, m) // m will have the same values, but this is an example - Go is not Groovy that supports dynamic vars
}
//Finally
if err := dbClient.Prisma.Transaction(vars...).Exec(ctx); err != nil {
    panic(err)
}
```

How would you advise one to handle batch inserts...?

**Comment by steebchen** [comment]
You should be able to use `var ops []transaction.Param` from github.com/prisma/prisma-client-go/runtime/transaction. This will need to be added to the docs.

**Comment by TheBeachMaster** [comment]
Nice, I'll close this once I have successfully tested this.

**Comment by TheBeachMaster** [comment]
This actually worked... Thanks @steebchen 

Soln:
```go
import "github.com/prisma/prisma-client-go/runtime/transaction"
// ...
ops := make([]transaction.Param, 0)

// ... statesInfo 

for _,s := range statesInfo{
m := dbClient.State.CreateOne(
  db.State.Name.Set(s.Name),
  db.State.Capital.Set(s.Capital),
).Tx()

ops = append(ops, m) 
}

if err := dbClient.Prisma.Transaction(ops...).Exec(ctx); err != nil {
    panic(err)
}
```
