### ISSUE TITLE
Support changing the generation output folder and package name

### ISSUE THREAD

**Issue by hi019** [prisma/prisma-client-go#542]
It would be great if we could customize the folder that `go run github.com/prisma/prisma-client-go generate` outputs to

**Comment by steebchen** [comment]
You can do that by specifying `output` in the generator block:

```prisma
generator client {
  provider         = "go run github.com/prisma/prisma-client-go"
  output           = "./your-folder"
  package          = "yourpackagename"
}
```

**Comment by hi019** [comment]
Oh, cool. I didn't see this noted in the docs, can I make a PR?

**Comment by steebchen** [comment]
Indeed, that is still missing. Sure, that'd be awesome. We do have this problem of fragmented docs as in theory this is [documented in the prisma docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path) but in reality Go users will not find this easily.
