### ISSUE TITLE
mocks: can't set expectations for FindMany

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#543]

**Comment by hi019** [comment]
I may be able to make a PR for this. Can I do something like this?

```go
func (m *userMockExec) ReturnsMany(v []UserModel) {
	*m.mock.Expectations = append(*m.mock.Expectations, mock.Expectation{
		Query: m.query,
		Want:  &v,
	})
}
```

**Comment by steebchen** [comment]
Yeah, I think that could work. I will most likely have some time left this week but if you want to send a PR today I'm happy to review and merge as soon as possible.

**Comment by hi019** [comment]
Sure, I'll send a PR today or tomorrow.

**Comment by hi019** [comment]
Unfortunately, I don't think I'll have time to implement this anytime soon :(
