### ISSUE TITLE
Remove all mentions of "photon"

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-client-go#615]
I see there are a couple places where "photon" is mentioned, it's now a 2+ years old name replaced by Prisma Client and we should do a small cleanup here probably.

https://sourcegraph.com/search?q=context:global+repo:github.com/prisma/+PHOTON+repo:%5Egithub%5C.com/prisma/prisma-client-go%24+&patternType=literal

**Comment by steebchen** [comment]
Agreed 😅
