### ISSUE TITLE
Sorting by multiple fields

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma-client-go#681]
So with my forum project, I have pinned posts. I wanted to write a query that would sort by created at date and then by pinned state so pinned posts are always at the top, this is what I wrote:

```go
	posts, err := d.db.Post.
		FindMany(filters...).
		With(
			db.Post.Author.Fetch(),
			db.Post.Tags.Fetch(),
			db.Post.Category.Fetch(),
		).
		Take(max).
		OrderBy(
			db.Post.CreatedAt.Order(db.Direction(sort)),
			db.Post.Pinned.Order(db.SortOrderAsc),
		).
		Exec(ctx)
```

Now one detail I wasn't sure about was sorting by a boolean, I did try with another date field just to rule that out and got the same error so I know it's not related to the type of the field.

Here's the error I got:

```
QueryParserError(QueryParserError {
    path: QueryPath {
        segments: ["Query", "findManyPost", "orderBy"]
    },
    error_kind: InputUnionParseError {
        parsing_errors: [
            QueryParserError {
                path: QueryPath {
                    segments: ["Query", "findManyPost", "orderBy"]
                },
                error_kind: ValueTypeMismatchError {
                    have: Object({
                        "createdAt": String("desc"),
                        "pinned": String("asc")
                    }),
                    want: Object(PostOrderByWithRelationInput)
                }
            },
            QueryParserError {
                path: QueryPath {
                    segments: ["Query", "findManyPost", "orderBy", "PostOrderByWithRelationInput"]
                },
                error_kind: FieldCountError(FieldCountError {
                    min: Some(0),
                    max: Some(1),
                    got: 2
                })
            }
        ]
    }
})
```

(also, minor thing, these errors I always have to manually format them in order to read what's going on - the format I assume is a direct format! call from Rust - it would be nice to get these errors in JSON or some custom `error` type in Go so they could be logged out in a more readable way! but that's just a QoL thing for another issue)

Anyway, for now I can just query pinned posts separately but this seems like a bug in the Go client as the prisma docs list multiple sort fields as an implemented feature of the query engine. Or maybe I'm doing something wrong!

**Comment by steebchen** [comment]
Thanks for reporting, I'm looking into it. Which version are you using?

**Comment by Southclaws** [comment]
Awesome, thank you! That was a quick fix!

I'll open an issue for the errors, it's not a huge issue, just a minor QoL thing, thanks!
