### ISSUE TITLE
Export With params interface

### ISSUE THREAD

**Issue by hi019** [prisma/prisma-client-go#684]
I would like to have a function that returns With params, like this:

```go
func (s *UserService) FindUserByID(ctx context.Context, id int, include dq.UserInclude) (*dq.User, error) {
	s.db.prisma.
		User.
		FindFirst(prisma.User.ID.Equals(id)).
		With(buildUserInclude(include)...)

   // ...
}

func buildUserInclude(include dq.UserInclude) []prisma.iUserRelationWith {
	return nil
}
```

But `prisma.iUserRelationWith` is not exported. As a workaround, as mentioned in #344, I can manually export `iUserRelationWith` under the generated directory.

**Comment by steebchen** [comment]
Sounds like something we should be able to add easily, do you think `UserRelationWith` is a good type name to export?

**Comment by hi019** [comment]
Works for me!
