### ISSUE TITLE
Create operation: code conciseness vs type-safety

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#7]
## 1) Concise code

```go
// create a new user and 2 posts
user, err := client.User.
	Create().
	// order does not matter
	SetName("John").
	SetAge(30).
	// maybe we forgot a field here, e.g. "email"? no way to know at compile time
	ConnectPosts(p1, p2).
	Save(ctx)
```

Using chains for setting values is very concise and clean. However, there is no way to verify that all required fields are specified.

## 2) Explicitly setting fields

```go
user, err := client.User.Create.Data(
	// Required fields first. The order is important here but it is 100% type safe!*
	User.Name.Set("John"),
	User.Age.Set(30),
	// the required parameters are fixed, which means we can't forget to set the email here
	User.Email.Set(30),
	// optional fields
	User.Address.Set("138 Charming Way"),
	User.Posts.Connect(p1),
	User.Posts.Connect(p2),
).Exec(ctx)
```

*The first argument has to be of the model "User", field name "Name" and type string, the second has to be the model "User", field "Age", type int, etc.

When you add a new required field to your sql schema, your Go build would not pass so you would be forced to add the new required field.

---

The explicit version is definitely the safer option, while the first version generally offers a very beautiful syntax and may be worth the trade off. Also, with the explicit version, the order is important and may be inconvenient to the user.

**Comment by steebchen** [comment]
Personally, I prefer the second option to be type-safe and force setting required fields.

**Comment by darioielardi** [comment]
Definitely agree.

**Comment by steebchen** [comment]
For the reasons listed above, we have for now decided to go with the explicit method.
