### ISSUE TITLE
Timed out fetching a connection from the pool (connection limit: 13, in use: 13)

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma-client-go#706]
Hey, recently launched a test of our site with a large userbase and this seems to happen after a short time of usage. Not sure what's going on as I can't find anywhere in the docs that mention the need to release/free connections explicitly.

```
pql error: Error in connector: Error creating a database connection. (Timed out fetching a connection from the pool (connection limit: 13, in use: 13))
```

Some details: The database is the default configured Postgres image, no changes to the connection limit. The pool size for Prisma is also left at the default (which I assume it uses the machine's API to count CPUs and do the math - which results in (6 x 2) + 1 = 13)

**Comment by Southclaws** [comment]
Okay I think I solved it myself, so I'll explain what I think was the issue:

Since we're migrating from an old system, the new system has two Prisma setups - one for the old DB schema and one for the new DB schema, and thus there are two sets of generated code and two Prisma clients.

Because there are two clients, with default settings, they both have a connection pool limit of 13 meaning my app can, worst case scenario, have 26 open connections to the single Postgres database (which contains the data for the old system and the new system, just in different table spaces)

So would this be the cause? Is this error actually from Postgres itself because the number of open connections exceeded the default limit of Postgres?

**Comment by steebchen** [comment]
This is from postgres itself. You can use pgbouncer if you need more connections. It's a bit complicated, you can also see how to increase the connection pool in Prisma: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool

**Comment by steebchen** [comment]
Let me know if it happens again though!

**Comment by Southclaws** [comment]
Alright even after I thought I knew what was wrong I woke up today to find the server had got stuck again.

It seems as soon as it hits this connection limit, the only solution is to restart the Go app. So it seems Prisma connections are remaining open even while no one is using the service.

Is it expected to use pgbouncer for a single app connecting to a single postgres database? there's no clusters or replication going on here, just a single server machine with one postgres container and one app container. `-c max_connections=100` is apparently the default for the postgres container image (though I'm not sure how to confirm the actual effective maximum on our running DB instance)

**Comment by steebchen** [comment]
Can you try adapting the settings in the link I sent? Specifically the `connection_limit`. With just a single app, you shouldn't need to use pgbouncer.

**Comment by steebchen** [comment]
First thing you should try though is upgrading to the latest client in the main branch. I have just bumped the Prisma CLI version to 3.7.0.

`go get github.com/prisma/prisma-client-go@main`

If you run into it again after using this version, try the things suggested above.

**Comment by Southclaws** [comment]
Thanks, it seems fixed now after a few days!

**Comment by steebchen** [comment]
Cool, feel free to re-open if you should run into it again.
