### ISSUE TITLE
Proposal: less verbose and useful error handling proposal

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#71]
Note: This is an idea and we don't know yet if it's useful or if we want to implement it. Please let us know in this issue if you think this is a good or a bad idea.

Go error handling is very explicit, but for good reasons. However, usually only explicit errors are important for our end users, for example a UniqueConstraintViolation. Our thinking was that usually you care about errors which are expected, but not which are unexpected and are not useful to test – where connection errors would fall into. For example, consider this:

```go
users, err := client.User.FindMany().Exec(ctx)

if err != nil {
	return fmt.Errorf("could not find users: %w", err)
}
```

If err can only contain fatal errors such as that the database connection is lost, it doesn’t really make sense to explicitly return an error since it’s unexpected, and it doesn’t make sense to check and create a specific error for each DB query you’re doing. It doesn’t add any additional value. For unexpected things, you usually panic. Since FindMany only reads from the database, there’s really nothing which can go wrong – expect having fatal errors:

```go
users := client.User.FindMany().Exec(ctx)
```

If the connection to the DB is lost, it panics. Usually, panics are handled by your webserver, or in a CLI case the program just exits.

Since we have just one possible error for FindOne (“ErrNotFound”), we could adapt this method to the following, since it’s not really an error per se:

```go
user, ok := client.User.FindOne().Exec(ctx)
if !ok {
	log.Printf("no user found")
} 
log.Printf("user: %+v", user)
```

I want to run this idea with more people, but in my previous Golang freelance project I’ve realised this would cleanup error checks a lot for all places where it’s just verbose but doesn’t provide any actual value. 

For write operations, an error is returned, since errors are expected here. How you can check for specific errors, such as a UniqueConstraintViolation is out of scope for this issue.

On the other hand, while it may be useful, it's also worth considering that this changes the API for the different methods. The API changes would look as follows (taken from [Matt's comment](https://github.com/prisma/prisma-client-go/issues/71#issuecomment-624552105)):

|                       **Before**                    | **After**                                 |
| :-------------------------------------------------- | :---------------------------------------- |
| `users, err := client.User.FindMany`                | `users := client.User.FindMany`           |
| `user, err := client.User.FindOne`                  | `user, ok := client.User.FindOne`         |
| `user, err := client.User.CreateOne`                | same                                      |
| `user, err := client.User.FindOne(...).Update(...)` | same                                      |
| `user, err := client.User.FindOne(...).Delete()`    | same                                      |

Maybe it's more useful to just return the errors as usual without panicking and rather have consistent API.

---

Full Go example: https://gist.github.com/steebchen/51ab929e04ae7436afca6b9d605e78f4

**Comment by matthewmueller** [comment]
Thanks for writing this up. I've read through the thread and I think understand the motivation: 

**Motivation:** you don't want to have to write 2 different if-statements for each call to check different error conditions

```go
user, err := prisma.User.FindOne()
if err != nil {
  if err == client.ErrUserNotFound {
    // do something here
  }
  // probably nothing we can do here
  return err
}
```

I agree this is verbose, but I don't think handling errors differently depending on the error is better

1. check if user is ok 
2. panic if database connection is lost

For 2), you might want to try reconnecting, logging an error message to your logging solution, etc.

My preference would be auto-generating helper functions:

```go
user, err := prisma.User.FindOne()
if prisma.IsUserNotFound(err) {
  // do something here
} else if err != nil {
 // probably nothing we can do here
  return err
}
```

**Comment by steebchen** [comment]
@matthewmueller not quite, the core motivation is how to provide good error handling, because it's an important topic and my experience is that with traditional ORMs it's incredibly hard to deal with errors. The non-verbosity is just a side effect of the FindOne() "ok" idea.

Regarding 2), I planned to handle reconnecting for the user there, it's something we should handle for the user. Only if that fails as well, it will panic.

My problem with not panicking is that the errors don't provide any additional value in almost all cases.

In a lot of my APIs, I end up writing exactly this code over and over again, and it does not add any more value:

```
if err != nil {
  return err
}
```

Most time, it's useful to wrap Go errors like `return fmt.Error("could not connect: %w", err)` to improve the error message. However, in this case I couldn't think of use cases where you expect this error or want to handle it "well".

Can you maybe give a few use cases for where panic may not be ideal?

**Comment by matthewmueller** [comment]
> Can you maybe give a few use cases for where panic may not be ideal? 

I think I agree with you that most times where panic is OK: network connections, dns issues, database issues, etc.

Let's look at it from another angle. One thing that would help me see this more clearly is a table of anticipated signature changes. I can kick if off:

|                       **Before**                        | **After** |
| :------------------------------------------------- | :--- |
|        `users, err := client.User.FindMany`         |       |
|         `user, err := client.User.FindOne`          |       |
|        `user, err := client.User.CreateOne`         |       |
| `user, err := client.User.FindOne(...).Update(...)` |       |
|  `user, err := client.User.FindOne(...).Delete()`   |       |

This API seems fairly clear to me, I'm not sure we'll make it more intuitive by changing up the return signature based one your query.

**Comment by hugbubby** [comment]
If what you're saying is that you want to change the go client so that it _panics_ if the connection to the database suddenly breaks or fails for a single query, then this seems like a monumentally terrible idea that would neuter the utility of the entire package. Connections go bad and reliable applications are built to handle those errors and retry or alert the user when appropriate. I do not want to have my CLI application or web servers "panic" at random moments because the internet was spotty one day.

Having named errors is fine, but just add the other errors in. You don't need to remove entire classes of erros and force your library's users to recover around prisma code.

**Comment by steebchen** [comment]
Thanks for your feedback. I think my argument here was that if you use another library which handles recovery already, like gorilla or gqlgen, it is kind of a nice solution, since you only get "expected" errors back, and "unexpected" errors are handled without explicitly handling them – by using recover which is already there (again, given that you use some library which does it). With this behaviour, retry logic would be already builtin, and it would only panic if the retries failed as well. You'd most likely still get alerted since you would get a panic, and error reporters would pick that up and you'd see it in your logs.

I agree with you though that this will probably more annoying for some users than it will solve problems for most users. We most likely won't implement this proposal anyway, it was just a random idea in the early days. Just using errors and checking them with named errors just like everyone else does is most certainly still the best way to go.

**Comment by steebchen** [comment]
Could you elaborate why you would like a *Must variant? It feels like to me you just extensively said you don't want random panics, but now you're suggesting a Must variant. I feel like inexperienced users will use *Must for everything even when they shouldn't, and they should definitely not have to choose between a normal query and a *Must query IMO (panicking on a row not found error or unique constraint violation doesn't seem useful).

**Comment by hugbubby** [comment]
> Could you elaborate why you would like a *Must variant? It feels like to me you just extensively said you don't want random panics, but now you're suggesting a Must variant. I feel like inexperienced users will use *Must for everything even when they shouldn't, and they should definitely not have to choose between a normal query and a *Must query IMO (panicking on a row not found error or unique constraint violation doesn't seem useful).

I wouldn't use it, for the aforementioned reasons - I like the fact that my programs handle database timeouts and the like. I was just suggesting it as an alternative to getting rid of "verbose" errors for everything. The *Must variants of errors could be the ones which only turn up "useful" errors ala RowNotFound, and the non-must variants would return the rest.

**Comment by steebchen** [comment]
Alright, thanks for the clarification. As I said we most likely will not implement this proposal anyway.

**Comment by steebchen** [comment]
Won't do anything here. It's fine as is.
