### ISSUE TITLE
Build ARM compatible CLI binaries

### ISSUE THREAD

**Issue by RobertCraigie** [prisma/prisma-client-go#717]
I've recently switched to an M1 mac and the currently binaries provided are not compatible with this chipset.

I do not know of the best solution for this as GitHub does not yet provide runners (https://github.com/actions/virtual-environments/issues/2187) so cross compilation is probably the only real possibility unless someone on the Prisma team would be willing to compile and publish the binaries themselves.

From having a look at the `pkg` README it sounds like it should be possible with something like the following command however I have not tested it.

```
npx pkg -t node17-darwin-arm64 --no-bytecode --public-packages "*" --public node_modules/prisma
```

This is relevant for Prisma Client Python as there is work being done to support ARM compiled engines: https://github.com/RobertCraigie/prisma-client-py/pull/233

**Comment by RobertCraigie** [comment]
This can actually be disregarded, I didn't know of Rosetta 2 which automatically translates the code from intel to M1.

Providing specific binaries for M1 would improve performance but is not strictly necessary.

**Comment by steebchen** [comment]
I have an M1 MacBook now. I can try to build arm64 Prisma CLI builds with pkg

**Comment by RobertCraigie** [comment]
Linux arm64 binaries would be great too, thank you :D

> in theory I could also upload builds with different node versions

I don't think we're going to support binaries with different node versions any time soon but that would be a welcome change too :)

> you @RobertCraigie have any input on how the binaries should be named

If you're wanting to stick to one node version I'd say to just try and stick to a similar naming scheme to the engine binaries, e.g.

M1 -> `darwin-arm64`
Linux aarch64 -> `linux-arm64`
Linux arm -> `linux-arm` (is this supported?)

And if you want to support multiple node versions you could use a similar naming schema to the OpenSSL engine versioning, e.g. `linux-arm64-node12`, `darwin-arm64-node16`

**Comment by RobertCraigie** [comment]
I've also been looking into automating the CLI binary building process, would that still be possible when targeting ARM?

**Comment by janpio** [comment]
Usually you can cross compile these, but sometimes you actually need a machine of the platform/architecture.

**Comment by steebchen** [comment]
Actually it is not at all :D

I published the binaries in the existing bucket with this scheme:

```
# x64
prisma-cli-$version-darwin-x64.gz
prisma-cli-$version-linux-x64.gz
prisma-cli-$version-windows-x64.exe.gz

# arm64
prisma-cli-$version-darwin-arm64.gz
prisma-cli-$version-linux-arm64.gz
prisma-cli-$version-windows-arm64.exe.gz
```

where `$version` is at least 3.13.0

I didn't test them though, so please let me know if they don't work.

**Comment by steebchen** [comment]
From 3.14.0 I will probably stop uploading the binaries like in the old scheme, and will use the scheme above

**Comment by RobertCraigie** [comment]
Thank you so much! @steebchen 

Unfortunately I'm not sure if I can really test the new binaries on my machine as I have Rosetta 2 installed and I can't find a reasonable method for uninstalling it :/

But it seems to work, thank you again :D

**Comment by Brendonovich** [comment]
> I didn't test them though, so please let me know if they don't work.

FWIW I've been using the x64 macOS and arm64 linux binaries with Prisma Client Rust and they seem to be working fine!

**Comment by steebchen** [comment]
Awesome! Thanks for letting me know @Brendonovich
