### ISSUE TITLE
Compatibility with gqlgen

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#73]
Often, the Prisma Go client is used to build APIs. When you use GraphQL, you can choose between many Go libraries – but [gqlgen](https://github.com/99designs/gqlgen) provides most typesafety because it follow a similar approach as Prisma does: generating code adapted to your schema.

However, Prisma and gqlgen do different things and have different goals. This means that it may not be as simple to use both tools together, but we want to make it as easy as possible. For example, gqlgen might generate different structs for your models than we do, meaning you have to convert between data structures manually.

We might not do anything while the Prisma Go client is in development. This means you might have to write all fields explicitly:

```go
func (r Resolver) User(ctx context.Context, id string) (User, error) {
  user, err := r.client.User.FindOne(db.User.ID.Equals(id)).Exec(ctx)
  // ...

  return User{
    ID: user.ID,
    Email: user.Email,
    Name: user.Name,
    // etc.
  }, nil
}
```

You can use both tools in your applications without problems, your code will usually just look more verbose. We may explore a few potential better solutions, such as:

- Fork gqlgen and build our own library. We can provide the best experience here but would need to maintain our own fork which is time-consuming and may split the community.
  ```return user, nil```
- Match our API to gqlgen's. This would provide a seamless experience for gqlgen users, but might limit the features of the Prisma Go client itself, especially when used without gqlgen. Also, if would need to keep compatibility with gqlgen's design decisions which might not fit our needs.
   ```return user, nil```
- Provide a gqlgen adapter library. This would be library maintained by us to easily convert between generated structs from Prisma and gqlgen types. We may still be limited by some features.
  ```return pgql.Convert(user), nil```

**Comment by steebchen** [comment]
The base structs are still incompatible, but you should be able to import the struct `Raw<model>`, e.g. for a model named `User` the struct would be called `RawUser`, and then access `.RawUser` in the returned struct when querying:

```go
func (UserResolver) User() (*db.RawUser, error) {
	user, err := client.User.FindOne().Exec(ctx)
	if err != nil {
		return nil, err
	}
	return &user.RawUser, err
}
```

**Comment by Nohac** [comment]
Would it be possible to use the [field collection](https://gqlgen.com/reference/field-collection/) from gqlgen based on the query to decide what fields and relations prisma should fetch?

I realize this issue is closed, so this question should probably be in separate issue.

**Comment by steebchen** [comment]
@Nohac Please create a new issue for that.

**Comment by maaft** [comment]
Just FYI: `Raw<model>` is not always working.

Example:
This is my gqlgen struct:
```golang
type User struct {
	CreatedAt      string     `json:"createdAt"`
	Email          string     `json:"email"`
	ID             string     `json:"id"`
	Password       string     `json:"password"`
	UpdatedAt      string     `json:"updatedAt"`
	Username       string     `json:"username"`
}

And this is my prisma `RawUser` struct:
```golang
type RawUser struct {
	ID             string   `json:"id"`
	CreatedAt      DateTime `json:"createdAt"`
	UpdatedAt      DateTime `json:"updatedAt"`
	Username       string   `json:"username"`
	Email          string   `json:"email"`
	Password       string   `json:"password"`
}
```

Prisma is using `DateTime` objects while gqlgen just uses plain `string`s.

**Comment by steebchen** [comment]
Hm, interesting. I think in order to this to work you would need to introduce a custom Date type in gqlgen by defining that in the schema and referencing the prisma DateTime scalar... not sure if that actually works in gqlgen right now though.
