### ISSUE TITLE
Stripped json

### ISSUE THREAD

**Issue by fragdance1** [prisma/prisma-client-go#757]
When working on Select statement I noticed that the returned json contains a lot of empty fields. Perhaps not a problem, but I like my json neat and tidy.

For instance, when using Select I get this:

![bild](https://user-images.githubusercontent.com/24291430/177203134-a4921be0-97ce-4925-a50c-6b1520665661.png)

i.e. overview, still etc are null, empty strings etc.

I've created an ExecJson-function (to be used instead of Exec) that returns the following json

![bild](https://user-images.githubusercontent.com/24291430/177203397-f9c375d1-9f51-4226-b010-82d8280ba888.png)

The one downside is that since we retrieve the data as json we can't do any manipulation (unless, of course, we unmarshal it, but that negates the whole thing), but if we just want to retrieve slim data this might be an idea?

**Comment by steebchen** [comment]
Can you elaborate what you are using this function for? Like why do you want to get raw json data instead of a type like User?

Also, can you elaborate what the exact signature of ExecJson would be?

**Comment by steebchen** [comment]
This is now available in the main branch, you can try it out by running `go get github.com/prisma/prisma-client-go@main`. It's not yet released, but I'll cut a new one soon!
