### ISSUE TITLE
eu-west-1 S3 is too away/slow from some countries

### ISSUE THREAD

**Issue by rinsuki** [prisma/prisma-client-go#793]
It seems you are using S3 on eu-west-1 for hosting a CLI binary.

https://github.com/prisma/prisma-client-go/blob/c04c00d11d675883f5fc79ddffda113183345904/binaries/binaries.go#L24-L25

but eu-west-1's S3 is too away from Japan (which I live in). I think this is physical constraints since Ireland is placed on the almost opposite side of the earth.

```
$ ping prisma-photongo.s3-eu-west-1.amazonaws.com
PING s3-r-w.eu-west-1.amazonaws.com (52.218.122.50): 56 data bytes
64 bytes from 52.218.122.50: icmp_seq=0 ttl=230 time=285.114 ms
64 bytes from 52.218.122.50: icmp_seq=1 ttl=230 time=287.899 ms
64 bytes from 52.218.122.50: icmp_seq=2 ttl=230 time=275.168 ms
```

also download from it is slow, it needs almost 2 minutes to download CLI in my environment.

```
$ curl -O https://prisma-photongo.s3-eu-west-1.amazonaws.com/prisma-cli-4.8.0-darwin-arm64.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.1M  100 44.1M    0     0   379k      0  0:01:59  0:01:59 --:--:--  884k
```

Could you provide CLI binaries from https://binaries.prisma.sh/ (using Cloudfront) or other CDN (or GitHub Releases, which is cached on Fastly) instead?

**Comment by janpio** [comment]
I can create a cloudfront distribution for that @steebchen so it works similar to binaries.prisma.sh. `packaged-cli.prisma.sh` maybe?

**Comment by rinsuki** [comment]
yeah It seems working better, 50x faster than S3!

**Comment by janpio** [comment]
Ok, then someone only needs to do a PR to this repository to remove the old URL with the new one and then this can be merged and released sooner or later.

**Comment by steebchen** [comment]
Thanks @janpio this is awesome! I will adapt the URLs later

**Comment by steebchen** [comment]
live via v0.17.0
