### ISSUE TITLE
Simple vs explicit syntax

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#8]
## 1) Simple syntax 

```go
// optional context
client = client.WithContext(ctx)

// query
products, err := client.Product.FindMany(
	Product.Where().NameContains("stuff"),
	Product.Where().PriceLt(10),
	Product.OrderBy().Price(ASC),
)
```

- No explicit context passing.
- One function (FindMany) handles everything, regardless of querying or ordering.
- "inline methods" such as `.Name("hi")`, `.NameContains("hi")`, `.PriceLt(5)`, etc.
- **Impossible to enforce required parameters when creating items**

## 2) Explicit syntax

```go
// query
products, err := client.Product.FindMany(
	Product.Name.Contains("stuff"),
	Product.Price.Lt(10),
).OrderBy(
	Product.Price.Asc(),
).Exec(ctx)
```

- **Pass a context explicitly for request cancellation and logging**
- It's more clear what gets queried (FindMany) and ordered (OrderBy), you can't mix and match here.
- Explicit methods: `.Name.Equals`, .`.Name.Contains`, `.Price.Lt`, `.Price.Gte`, etc.
- **Major advantage: type-safe create operations for required parameters are possible.**

---

## Summary

Please note that not all things belong to one specific option – in theory we could mix and match like we want, but to keep it simple I grouped a few decisions for each syntax.

The major differences are the explicit context passing and the explicit Where & OrderBy syntax.

The request context passing is only constantly forced in the second option, which is not super beautiful but enforces passing it everywhere. For more information about context, see #6.

The syntax difference is having all arguments in a single function (FindMany) or separated by Where & OrderBy. In the first option you can mix and match it, in the second option it's separated. It's also required to use Where() and OrderBy() in the first option all the time, whereas in the second option you use field methods such as `Product.Price.Lt(5)` or `Product.Price.Asc()`.

### More examples

```go
// Simple syntax. Very clean!
u, err := user.Create(
	user.New().
		SlackID(u.SlackID).
		Username(u.Username).
		Email(u.Email).
		FirstName(u.FirstName).
		LastName(u.LastName).
		AvatarURL(u.AvatarURL).
		Timezone(u.Timezone).
		IsTeamOwner(true).
		TeamID(tm.ID),
)

// vs

// Explicit syntax. Fixed parameters, impossible to forget required parameters.
user, err := client.User.Create(
	User.SlackID.Set(u.SlackID),
	User.TeamID.Set("123"),
	User.Username.Set(u.Username),
	User.Email.Set(u.Email),
	User.FirstName.Set(u.FirstName),
	User.LastName.Set(u.LastName),
	User.AvatarURL.Set(u.AvatarURL),
	User.Timezone.Set(u.Timezone),
	User.IsTeamOwner.Set(true),
	User.TeamID.Set(tm.ID),
).Exec(ctx)
```

**Comment by darioielardi** [comment]
I definitely prefer the explicit form. 
I think separation between, for example, `where` and `order by` parameters makes everything more readable. Same with `.NameContains()` vs `.Name.Contains()`.
Also, in my opinion the possibility to have type-safe create operations for required parameters is a must have.
