### ISSUE TITLE
Problem when using reserved go keywords

### ISSUE THREAD

**Issue by Nohac** [prisma/prisma-client-go#91]
If any of [go's reserved keywords](https://golang.org/ref/spec#Keywords) are used as a field name,  whenever the lowercase version of that is used when generating code, you'll get a syntax error.

There needs to be some sort of safeguard in place so that the names don't collide. I suggest just prepending the words with an additional character. Example: `type` -> `ttype` etc.

**Comment by steebchen** [comment]
Can you provide an example where this breaks the code?

**Comment by Nohac** [comment]
It happens when model fields are used as function parameters.

Here's a simple schema to demonstrate the issue:
```graphql
generator db {
  provider = "go run github.com/prisma/prisma-client-go"
  output = "./db/db_gen.go"
  package = "db"
}

enum UserType {
  ADMIN
  USER
} 

model User {
  id String @id @default(cuid())
  email String @unique
  name String?
  type UserType
}
```

When running the generate command, I get this error:
```
	// Creates a single user.
	func (r userActions) CreateOne(
		// { }
				email userEmailSetParams,// { }
				type userTypeSetParams,
		optional ...userSetParams,
	) userCreateOne {
		var v userCreateOne
		v.query.Client = r.client
		var fields []builder.Field
		
		fields = append(fields, email.data)
		
		fields = append(fields, type.data)
		
		for _, q := range optional {
			fields = append(fields, q.data)
		}
		v.query.Inputs = append(v.query.Inputs, builder.Input{
			Name:   "data",
			Fields: fields,
		})
		return v
	}
	type userCreateOne struct {
		query builder.Query
	}
	func (r userCreateOne) Exec(ctx context.Context) (UserModel, error) {
		r.query.Operation = "mutation"
		r.query.Method = "createOne"
		r.query.Model = "User"
		r.query.Outputs = userOutput
		var v createOneUserResponse
		err := r.query.Exec(ctx, &v)
		if v.Errors != nil {
			first := v.Errors[0]
			return UserModel{}, fmt.Errorf(first.Message)
		}
		return v.Data.CreateOneUser, err
	}
 from file create.gotpl: 238:5: expected 'IDENT', found 'type' (and 10 more errors)
exit status 1
```

Notice that the name of one of the `CreateOne` function parameters are named `type`. This issue happens for all the reserved keywords I linked to earlier.

**Comment by steebchen** [comment]
Thanks for the additional info. Will look into it next week

**Comment by Nohac** [comment]
I did make a quick-fix for this locally, should I open a PR?

**Comment by steebchen** [comment]
I'm currently struggling between just renaming these reserver keywords, such as type to ttype, or if I want to avoid that and just prefix the parameters with an underscore (so type becomes _type). What's your opinion about this @Nohac?

**Comment by Nohac** [comment]
@steebchen I thought tools like `golint` etc. would complain if you had `_` in variable names, but I checked, and it seems like it's fine with using `_` as a prefix. I have never really seen `_` being used in any go code I've read before, I've only seen things like `typ` and `ttype` being used in those situations, but since this is a bit deferent, I'd say go with `_` since it should probably be a close to the original field name as possible.

**Comment by steebchen** [comment]
Yeah I agree. Plus, the change is super simple (literally one char) and we don't need to introduce another library. We may re-visit when there's need for these variables in more places.
